// data.js
const TITLES = [
  {
    id: 'frieren-2023',
    title: 'Фрирен, провожающая в последний путь',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2023, 2026)\nСезон 3 «Золотые земли» — анонсирован, премьера в октябре 2027 года.',
    year: 2023,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Эльфийка-магиня Фрирен, пережившая своих спутников по приключениям, заново открывает для себя, что значит ценить недолгую человеческую жизнь.',
    cover: 'images/covers/frieren-2023.jpg',
    parts: [
      { name: 'Сезон 1', year: 2023, released: true },
      { name: 'Сезон 2', year: 2026, released: true },
      { name: 'Сезон 3 «Золотые земли»', year: 2027, released: false }
    ]
  },
  {
    id: 're-zero-starting-life-in-another-world-2016',
    title: 'Re:ZERO — Жизнь с нуля в альтернативном мире',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '4 сезона (2016–2026) и 2 OVA-фильма (2018, 2019)\nСезон 4 выходит двумя частями: «Утрата» (апрель–июнь 2026) и «Возвращение» — с 12 августа 2026, ещё в эфире.',
    year: 2016,
    genres: ['фэнтези', 'триллер'],
    rating: null,
    synopsis: 'Субару переносится в фэнтезийный мир и обнаруживает, что может возвращаться в прошлое после смерти — но каждый раз платит за это дорогую цену.',
    cover: 'images/covers/re-zero-starting-life-in-another-world-2016.jpg',
    parts: [
      { name: 'Сезон 1', year: 2016, released: true },
      { name: 'OVA «Memory Snow»', year: 2018, released: true },
      { name: 'OVA «Ледяные узы»', year: 2019, released: true },
      { name: 'Сезон 2', year: 2020, released: true },
      { name: 'Сезон 3', year: 2024, released: true },
      { name: 'Сезон 4, часть 1 «Утрата»', year: 2026, released: true },
      { name: 'Сезон 4, часть 2 «Возвращение»', year: 2026, released: false }
    ]
  },
  {
    id: 'the-boys-2019',
    title: 'Пацаны',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '5 сезонов (2019–2026), сериал завершён — финал вышел 20 мая 2026 года.',
    year: 2019,
    genres: ['сатира', 'боевик'],
    rating: null,
    synopsis: 'Группа мстителей без суперсил охотится на коррумпированных супергероев корпорации Vought.',
    cover: 'images/covers/the-boys-2019.jpg',
    parts: [
      { name: 'Сезон 1', year: 2019, released: true },
      { name: 'Сезон 2', year: 2020, released: true },
      { name: 'Сезон 3', year: 2022, released: true },
      { name: 'Сезон 4', year: 2024, released: true },
      { name: 'Сезон 5 (финальный)', year: 2026, released: true }
    ]
  },
  {
    id: 'ted-lasso-2020',
    title: 'Тед Лассо',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '4 сезона (2020–2023, 2026)\nСезон 4 выходит еженедельно с 5 августа по 7 октября 2026 года.',
    year: 2020,
    genres: ['комедия', 'спорт'],
    rating: null,
    synopsis: 'Американский тренер по американскому футболу без опыта в футболе возглавляет английский клуб и меняет отношение команды друг к другу.',
    cover: 'images/covers/ted-lasso-2020.jpg',
    parts: [
      { name: 'Сезон 1', year: 2020, released: true },
      { name: 'Сезон 2', year: 2021, released: true },
      { name: 'Сезон 3', year: 2023, released: true },
      { name: 'Сезон 4', year: 2026, released: true }
    ]
  },
  {
    id: 'barbie-2023',
    title: 'Барби',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['комедия', 'фэнтези'],
    rating: null,
    synopsis: 'Барби покидает идеальный Барбиленд и отправляется в реальный мир, где сталкивается с непростыми вопросами об идентичности.',
    cover: 'images/covers/barbie-2023.jpg'
  },
  {
    id: 'fight-club-1999',
    title: 'Бойцовский клуб',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1999,
    genres: ['драма', 'триллер'],
    rating: null,
    synopsis: 'Безымянный офисный работник и харизматичный продавец мыла Тайлер Дёрден основывают подпольный бойцовский клуб, который перерастает в нечто гораздо большее.',
    cover: 'images/covers/fight-club-1999.jpg'
  },
  {
    id: 'it-takes-two-2021',
    title: 'It Takes Two',
    category: 'game',
    status: 'done',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2021,
    genres: ['кооператив', 'платформер'],
    rating: null,
    synopsis: 'Разводящиеся родители превращаются в кукол и должны пройти изобретательные кооперативные головоломки, чтобы вернуть себе человеческий облик.',
    cover: 'images/covers/it-takes-two-2021.jpg'
  },
  {
    id: 'baldurs-gate-3-2023',
    title: "Baldur's Gate 3",
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Mac', 'PS5', 'Xbox Series X/S'],
    year: 2023,
    genres: ['ролевая игра', 'фэнтези'],
    rating: null,
    synopsis: 'Партийная RPG по мотивам D&D: отряд заражённых мозговым паразитом иллитидов пытается остановить вторжение разума в Забытых Королевствах.',
    cover: 'images/covers/baldurs-gate-3-2023.jpg'
  },
  {
    id: 'tengen-toppa-gurren-lagann-2007',
    title: 'Гуррен-Лаганн',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2007, 27 серий) и 2 полнометражных фильма (2008–2009); история полностью завершена, продолжение не планируется.',
    year: 2007,
    genres: ['меха', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Симон и Камина сбегают из подземной деревни на пилотируемом роботе Лагann и присоединяются к восстанию против таинственных врагов на поверхности — история взросления перерастает в эпическую сагу о человеческой воле.',
    cover: 'images/covers/tengen-toppa-gurren-lagann-2007.png',
    parts: [
      { name: 'Сезон 1', year: 2007, released: true },
      { name: 'Фильм 1 «Прорыв в небеса»', year: 2008, released: true },
      { name: 'Фильм 2 «Огни в небе — это звёзды»', year: 2009, released: true }
    ]
  },
  {
    id: 'demon-slayer-kimetsu-no-yaiba-2019',
    title: 'Клинок, рассекающий демонов',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '4 сезона (2019–2024) и 2 фильма; трилогия «Замок Бесконечности» начата в 2025 году\nЧасть 2 ожидается в 2027 году, часть 3 — в 2029-м; точные даты не объявлены.',
    year: 2019,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Тандзиро становится истребителем демонов, чтобы отомстить за погибшую семью и найти способ вернуть человеческий облик своей сестре Незуко, ставшей демоном.',
    cover: 'images/covers/demon-slayer-kimetsu-no-yaiba-2019.jpg',
    parts: [
      { name: 'Сезон 1', year: 2019, released: true },
      { name: 'Фильм «Бесконечный поезд»', year: 2020, released: true },
      { name: 'Сезон 2 «Квартал красных фонарей»', year: 2021, released: true },
      { name: 'Сезон 3 «Деревня кузнецов»', year: 2023, released: true },
      { name: 'Сезон 4 «Тренировка столпов»', year: 2024, released: true },
      { name: 'Фильм «Замок Бесконечности», часть 1', year: 2025, released: true },
      { name: 'Фильм «Замок Бесконечности», часть 2', year: 2027, released: false },
      { name: 'Фильм «Замок Бесконечности», часть 3', year: 2029, released: false }
    ]
  },
  {
    id: 'ride-your-wave-2019',
    title: 'На твоей волне',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2019,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'После гибели возлюбленного-серфингиста девушка обнаруживает, что может снова видеть и слышать его — но только когда рядом есть вода.',
    cover: 'images/covers/ride-your-wave-2019.jpg'
  },
  {
    id: 'witch-hat-atelier-2026',
    title: 'Ателье колдовских колпаков',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (апрель–июнь 2026)\nСезон 2 — официально анонсирован и в производстве (после серии 13, 29 июня 2026); дата премьеры ещё не названа, ожидается не раньше 2027–2028 года.',
    year: 2026,
    genres: ['фэнтези', 'драма', 'приключения'],
    rating: null,
    synopsis: 'Девочка Коко мечтает стать волшебницей в мире, где магии учат лишь избранных по рождению, — пока не встречает ведьму, владеющую тайным искусством рисованных заклинаний.',
    cover: 'images/covers/witch-hat-atelier-2026.jpg',
    parts: [
      { name: 'Сезон 1', year: 2026, released: true },
      { name: 'Сезон 2', year: null, released: false }
    ]
  },
  {
    id: 'cyberpunk-edgerunners-2022',
    title: 'Киберпанк: Бегущие по краю',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (2022, 10 серий), история завершена\n«Edgerunners 2» — самостоятельная история с новым составом персонажей, премьера на Netflix осенью 2026 года.',
    year: 2022,
    genres: ['боевик', 'драма', 'фантастика'],
    rating: null,
    synopsis: 'Уличный парень Дэвид Мартинес становится кибер-модифицированным наёмником-эджраннером, чтобы выжить в жестоком мире Найт-Сити, но каждая аугментация приближает его к безумию киберпсихоза.',
    cover: 'images/covers/cyberpunk-edgerunners-2022.jpg',
    parts: [
      { name: 'Сезон 1', year: 2022, released: true },
      { name: '«Edgerunners 2»', year: 2026, released: false }
    ]
  },
  {
    id: 'a-silent-voice-2016',
    title: 'Форма голоса',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Бывший школьный хулиган пытается искупить вину перед глухой одноклассницей, которую когда-то травил, и заново научиться понимать людей вокруг себя.',
    cover: 'images/covers/a-silent-voice-2016.jpg'
  },
  {
    id: 'josee-the-tiger-and-the-fish-2020',
    title: 'Её заветное желание',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2020,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Студент подрабатывает помощником девушки, прикованной к инвалидному креслу и живущей в мире своих фантазий, и постепенно открывает для неё — и для себя — большой мир.',
    cover: 'images/covers/josee-the-tiger-and-the-fish-2020.jpg'
  },
  {
    id: 'your-name-2016',
    title: 'Твоё имя',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Токийский парень и провинциальная школьница неожиданно начинают периодически меняться телами и постепенно понимают, что их связывает нечто большее, чем случайность.',
    cover: 'images/covers/your-name-2016.png'
  },
  {
    id: 'devil-may-cry-2025',
    title: 'Дьявол может плакать',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2025, 2026)\nСезон 3 «Paradiso» — заключительный, официально подтверждён; дата премьеры пока не объявлена (ориентировочно не раньше весны 2027 года).',
    year: 2025,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Получеловек-полудемон Данте сражается с силами ада, пытаясь остановить открытие врат в мир людей и разгадать тайну своего происхождения — взрослая экранизация культовой игровой серии от Netflix.',
    cover: 'images/covers/devil-may-cry-2025.jpg',
    parts: [
      { name: 'Сезон 1', year: 2025, released: true },
      { name: 'Сезон 2', year: 2026, released: true },
      { name: 'Сезон 3 «Paradiso»', year: null, released: false }
    ]
  },
  {
    id: 'shaman-king-2021',
    title: 'Король шаманов',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '2 сезона: ремейк (2021–2022, 52 серии) и сиквел «Flowers» (2024, 13 серий); история завершена, новых анонсов по аниме нет.',
    year: 2021,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Ремейк классического аниме о мальчике-шамане Йо Асакуре, который готовится к турниру шаманов, чтобы стать королём духов и изменить мир.',
    cover: 'images/covers/shaman-king-2021.png',
    parts: [
      { name: 'Сезон 1 (ремейк)', year: 2021, released: true },
      { name: 'Сезон 2 «Flowers»', year: 2024, released: true }
    ]
  },
  {
    id: "jojo-s-bizarre-adventure-2012",
    title: 'Невероятные приключения ДжоДжо',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '7 из 9 частей манги экранизировано (2012–2026)\n«Steel Ball Run» стартовал спецэпизодом в марте 2026, еженедельный показ 2–3 глав — с 25 сентября 2026; часть 8 «JoJolion» пока не анонсирована.',
    year: 2012,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Многопоколенная сага о семье Джостар, чьи представители сражаются со сверхъестественными врагами при помощи уникальных способностей — Стендов.',
    cover: 'images/covers/jojo-s-bizarre-adventure-2012.jpg',
    parts: [
      { name: 'Сезон 1 «Phantom Blood» / «Battle Tendency»', year: 2012, released: true },
      { name: 'Сезон 2 «Stardust Crusaders»', year: 2014, released: true },
      { name: 'Сезон 3 «Diamond is Unbreakable»', year: 2016, released: true },
      { name: 'Сезон 4 «Golden Wind»', year: 2018, released: true },
      { name: 'Сезон 5 «Stone Ocean»', year: 2021, released: true },
      { name: 'Сезон 6 «Steel Ball Run»', year: 2026, released: true }
    ]
  },
  {
    id: 'noragami-2014',
    title: 'Бездомный Бог',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '2 сезона и OVA (2014–2015); несмотря на завершение манги в 2024 году, продолжение аниме не анонсировано.',
    year: 2014,
    genres: ['боевик', 'сверхъестественное', 'комедия'],
    rating: null,
    synopsis: 'Мелкий бог Ято мечтает о собственном святилище и толпах почитателей, а пока подрабатывает, выполняя случайные просьбы людей за пять йен, — пока не встречает школьницу Хиёри, застрявшую между миром людей и духов.',
    cover: 'images/covers/noragami-2014.jpg',
    parts: [
      { name: 'Сезон 1', year: 2014, released: true },
      { name: 'OVA', year: 2014, released: true },
      { name: 'Сезон 2 «Aragoto»', year: 2015, released: true }
    ]
  },
  {
    id: 'violet-evergarden-2018',
    title: 'Вайолет Эвергарден',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2018, 13 серий) и фильм-продолжение (2020); история полностью завершена, новых анонсов нет.',
    year: 2018,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Бывшая девочка-солдат Виолетта Эвергарден устраивается автором писем на заказ и учится понимать человеческие чувства, включая смысл слов «я люблю тебя», сказанных ей человеком, которого она потеряла на войне.',
    cover: 'images/covers/violet-evergarden-2018.png',
    parts: [
      { name: 'Сезон 1', year: 2018, released: true },
      { name: 'Фильм-продолжение', year: 2020, released: true }
    ]
  },
  {
    id: 'that-time-i-got-reincarnated-as-a-slime-2018',
    title: 'О моём перерождении в слизь',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '3 сезона (2018–2024) и фильм (2022)\nСезон 4 — выходит с апреля по сентябрь 2026 года\nВторой фильм — вышел в феврале 2026 года',
    year: 2018,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Погибший японский офисный работник перерождается в фэнтезийном мире слизью и, получив уникальные способности, строит собственное государство монстров, где разные виды могут жить в мире.',
    cover: 'images/covers/that-time-i-got-reincarnated-as-a-slime-2018.jpg',
    parts: [
      { name: 'Сезон 1', year: 2018, released: true },
      { name: 'Сезон 2', year: 2021, released: true },
      { name: 'Фильм «Scarlet Bond»', year: 2022, released: true },
      { name: 'Сезон 3', year: 2024, released: true },
      { name: 'Фильм 2 «Tears of the Azure Sea»', year: 2026, released: true },
      { name: 'Сезон 4', year: 2026, released: true }
    ]
  },
  {
    id: "hell-s-paradise-jigokuraku-2023",
    title: 'Адский рай',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2023, 2026), адаптировано около 90 из 127 глав манги; третий сезон ожидается, но студией MAPPA пока официально не подтверждён.',
    year: 2023,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Приговорённый к смерти ниндзя Габимару получает шанс на помилование, если найдёт эликсир бессмертия на таинственном острове, кишащем чудовищами.',
    cover: 'images/covers/hell-s-paradise-jigokuraku-2023.jpg',
    parts: [
      { name: 'Сезон 1', year: 2023, released: true },
      { name: 'Сезон 2', year: 2026, released: true }
    ]
  },
  {
    id: 'chainsmoker-cat-2026',
    title: 'Табакошка',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон, выходит еженедельно с 3 июля 2026 года; о продлении на второй сезон пока не сообщалось.',
    year: 2026,
    genres: ['комедия', 'повседневность'],
    rating: null,
    synopsis: 'Кошкодевочка Яни с пагубной привычкой к курению никак не может навести порядок ни в квартире, ни в жизни — комедийное аниме по манге NyanNyanFactory, известное также под рабочим русским названием «Табакошка».',
    cover: 'images/covers/chainsmoker-cat-2026.jpg'
  },
  {
    id: 'a-new-dawn-2026',
    title: 'И наступит рассвет',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2026,
    genres: ['драма', 'мистика'],
    rating: null,
    synopsis: 'Режиссёрский дебют Ёситоси Синономии (аниматора «Твоего имени» и «Сада изящных слов») — история о двух друзьях детства, воссоединившихся у заброшенной фабрики фейерверков, которой грозит снос. В российском прокате известен под названием «И наступит рассвет».',
    cover: 'images/covers/a-new-dawn-2026.jpg'
  },
  {
    id: 'suzume-2022',
    title: 'Судзумэ, закрывающая двери',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2022,
    genres: ['приключения', 'фэнтези', 'мистика'],
    rating: null,
    synopsis: 'Школьница Судзумэ встречает загадочного юношу, ищущего двери, запечатывающие катастрофы, и вместе с говорящим стулом отправляется в путешествие по Японии, чтобы остановить бедствия, вырывающиеся из потустороннего мира.',
    cover: 'images/covers/suzume-2022.jpg'
  },
  {
    id: 'avatar-the-last-airbender-2005',
    title: 'Аватар: Легенда об Аанге (2005)',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '3 сезона («Книги», 2005–2008), сериал полностью завершён; прямых продолжений нет, только спин-оффы вроде «Легенды о Корре».',
    year: 2005,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Классический мультсериал Nickelodeon об Аанге — последнем аватаре, способном покорять все четыре стихии, который должен освоить магию воды, земли и огня, чтобы остановить Народ Огня и восстановить баланс в мире.',
    cover: 'images/covers/avatar-the-last-airbender-2005.jpg',
    parts: [
      { name: 'Книга 1: Вода', year: 2005, released: true },
      { name: 'Книга 2: Земля', year: 2006, released: true },
      { name: 'Книга 3: Огонь', year: 2007, released: true }
    ]
  },
  {
    id: 'avatar-the-last-airbender-2024',
    title: 'Аватар: Легенда об Аанге (2024)',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2024, 2026)\nСезон 3 — заключительный, съёмки завершены в ноябре 2025 года, идёт постпродакшен; премьера ожидается летом 2027 года (ближе к концу второго квартала), точная дата пока не объявлена.',
    year: 2024,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Игровой ремейк культового мультсериала о мальчике-аватаре Аанге, который пробуждается спустя сто лет после начала войны Народа Огня и должен научиться покорять все стихии, чтобы спасти мир.',
    cover: 'images/covers/avatar-the-last-airbender-2024.jpg',
    parts: [
      { name: 'Сезон 1', year: 2024, released: true },
      { name: 'Сезон 2', year: 2026, released: true },
      { name: 'Сезон 3', year: 2027, released: false }
    ]
  },
  {
    id: 'avatar-aang-the-last-airbender-2026',
    title: 'Легенда об Аанге: Последний маг воздуха',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Полнометражный анимационный фильм студии Avatar Studios, продолжающий события оригинального сериала: Аанг, последний маг воздуха, узнаёт о древней силе, способной спасти культуру его исчезнувшего народа от забвения, и вместе с друзьями отправляется на поиски, пока эта сила не попала в чужие руки.',
    cover: 'images/covers/avatar-aang-the-last-airbender-2026.jpg'
  },
  {
    id: 'castlevania-2017',
    title: 'Кастлвания',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '4 сезона (2017–2021), сериал полностью завершён; прямое продолжение истории — «Castlevania: Nocturne».',
    year: 2017,
    genres: ['тёмное фэнтези', 'боевик', 'ужасы'],
    rating: null,
    synopsis: 'Мрачная анимационная адаптация видеоигр Castlevania: Тревор Бельмонт, последний из проклятого рода охотников на чудовищ, сражается с вампиром Дракулой, объявившим войну человечеству после гибели своей жены-целительницы.',
    cover: 'images/covers/castlevania-2017.jpg',
    parts: [
      { name: 'Сезон 1', year: 2017, released: true },
      { name: 'Сезон 2', year: 2018, released: true },
      { name: 'Сезон 3', year: 2020, released: true },
      { name: 'Сезон 4', year: 2021, released: true }
    ]
  },
  {
    id: 'castlevania-nocturne-2023',
    title: 'Кастлвания: Ноктюрн',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2023, 2025)\nСудьба сериала неясна: Netflix больше полутора лет не продлевает и официально не закрывает его; источники по состоянию на июнь 2026 считают продолжение маловероятным.',
    year: 2023,
    genres: ['тёмное фэнтези', 'боевик', 'ужасы'],
    rating: null,
    synopsis: 'Прямое продолжение «Кастлвании»: во Франции конца XVIII века, спустя триста лет после первых событий, потерявший магию Рихтер Бельмонт вместе с Марией Ренар и Аннет должен остановить Эрзебет Батори — вампиршу, стремящуюся стать «мессией» и погрузить мир во тьму.',
    cover: 'images/covers/castlevania-nocturne-2023.jpg',
    parts: [
      { name: 'Сезон 1', year: 2023, released: true },
      { name: 'Сезон 2', year: 2025, released: true }
    ]
  },
  {
    id: 'the-legend-of-vox-machina-2022',
    title: 'Легенда о Vox Machina',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '4 сезона (2022–2024, 2026)\nСезон 5 — заключительный, подтверждён; премьера 16 июня 2027 года.',
    year: 2022,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Анимационная адаптация первой кампании настольного шоу Critical Role: банда из восьми неидеальных наёмников-героев Vox Machina защищает мир Экзандрии от тёмных магических сил.',
    cover: 'images/covers/the-legend-of-vox-machina-2022.jpg',
    parts: [
      { name: 'Сезон 1', year: 2022, released: true },
      { name: 'Сезон 2', year: 2023, released: true },
      { name: 'Сезон 3', year: 2024, released: true },
      { name: 'Сезон 4', year: 2026, released: true },
      { name: 'Сезон 5 (финальный)', year: 2027, released: false }
    ]
  },
  {
    id: 'the-mighty-nein-2025',
    title: 'Могучая девятка',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (ноябрь 2025, 8 серий)\nСезон 2 — утверждён (снимался одновременно с первым) и почти готов, целевое окно — конец 2026 года, точная дата премьеры на Prime Video пока не объявлена.',
    year: 2025,
    genres: ['фэнтези', 'приключения', 'драма'],
    rating: null,
    synopsis: 'Анимационная экранизация второй кампании Critical Role: группа беглецов и изгоев из Волшебных Земель случайно завладевает могущественным артефактом и вынуждена объединиться, чтобы спасти реальность от катастрофы.',
    cover: 'images/covers/the-mighty-nein-2025.jpg',
    parts: [
      { name: 'Сезон 1', year: 2025, released: true },
      { name: 'Сезон 2', year: null, released: false }
    ]
  },
  {
    id: 'money-heist-2017',
    title: 'Бумажный дом',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '5 сезонов, сериал полностью завершён (2017–2021; финал вышел двумя частями); продолжений не планируется.',
    year: 2017,
    genres: ['криминал', 'драма', 'триллер'],
    rating: null,
    synopsis: 'Загадочный человек по прозвищу Профессор собирает банду из восьми грабителей в масках Дали для беспрецедентного ограбления Королевского монетного двора Испании, которое перерастает в затяжное противостояние с полицией.',
    cover: 'images/covers/money-heist-2017.jpg',
    parts: [
      { name: 'Сезон 1', year: 2017, released: true },
      { name: 'Сезон 2', year: 2018, released: true },
      { name: 'Сезон 3', year: 2019, released: true },
      { name: 'Сезон 4', year: 2020, released: true },
      { name: 'Сезон 5, часть 1', year: 2021, released: true },
      { name: 'Сезон 5, часть 2', year: 2021, released: true }
    ]
  },
  {
    id: 'gen-v-2023',
    title: 'Поколение «Ви»',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '2 сезона (2023, 2025); сериал закрыт Amazon в апреле 2026 года, сюжетные линии продолжатся в «Пацанах» и других проектах вселенной.',
    year: 2023,
    genres: ['супергерои', 'сатира', 'драма'],
    rating: null,
    synopsis: 'Спин-офф «Пацанов» о студентах Готолкинского университета — единственного колледжа для супергероев, — которые борются за популярность и оценки, пока не сталкиваются с чем-то куда более зловещим, творящимся за стенами кампуса.',
    cover: 'images/covers/gen-v-2023.jpg',
    parts: [
      { name: 'Сезон 1', year: 2023, released: true },
      { name: 'Сезон 2', year: 2025, released: true }
    ]
  },
  {
    id: 'masters-of-the-universe-revelation-2021',
    title: 'Властелины вселенной: Откровение',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '1 мини-сериал, 2 части (2021, 10 серий), сюжет завершён; прямое продолжение — «Revolution».',
    year: 2021,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'После катастрофической битвы Хи-Мэна со Скелетором Этерния расколота, а Хранители Серого Черепа рассеяны. Тила должна собрать разрозненных героев и найти пропавший Меч Силы, пока мир не погрузился в хаос, — и раскрыть тайну, которую от неё скрывали.',
    cover: 'images/covers/masters-of-the-universe-revelation-2021.jpg',
    parts: [
      { name: 'Часть 1', year: 2021, released: true },
      { name: 'Часть 2', year: 2021, released: true }
    ]
  },
  {
    id: 'masters-of-the-universe-revolution-2024',
    title: 'Властелины вселенной: Революция',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2024, 5 серий), сериал завершён; продолжение не анонсировано.',
    year: 2024,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Прямое продолжение «Откровения»: технологии против магии — механизированный Скелетор, обретший мощь искусственного интеллекта Матплаты, обрушивается на сердце Этернии, а принц Адам разрывается между троном и мечом, решая, кем ему быть — королём или Хи-Мэном.',
    cover: 'images/covers/masters-of-the-universe-revolution-2024.jpg'
  },
  {
    id: 'the-amazing-spider-man-2012',
    title: 'Новый Человек-паук',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2012,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер получает суперспособности после укуса радиоактивного паука и, распутывая тайну исчезновения отца, впервые сталкивается с Ящером — учёным, одержимым генетическими экспериментами.',
    cover: 'images/covers/the-amazing-spider-man-2012.jpg'
  },
  {
    id: 'the-amazing-spider-man-2-2014',
    title: 'Новый Человек-паук: Высокое напряжение',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер пытается совмещать жизнь супергероя и отношения с Гвен Стейси, но городу угрожают электрический злодей Электро и бывший друг Гарри Озборн, вставший на путь Зелёного гоблина.',
    cover: 'images/covers/the-amazing-spider-man-2-2014.jpg'
  },
  {
    id: 'superman-2025',
    title: 'Супермен',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Молодой Супермен пытается совместить свою человечность с наследием криптонца, сражаясь с олигархом Лексом Лютором и отстаивая идеалы добра в циничном мире, — первый фильм новой киновселенной DC Джеймса Ганна.',
    cover: 'images/covers/superman-2025.jpg'
  },
  {
    id: 'the-gentlemen-2019',
    title: 'Джентльмены',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2019,
    genres: ['криминал', 'комедия', 'боевик'],
    rating: null,
    synopsis: 'Американец, построивший в Британии империю по выращиванию марихуаны, решает продать бизнес и отойти от дел, что запускает цепь интриг, шантажа и предательств среди лондонского криминального мира.',
    cover: 'images/covers/the-gentlemen-2019.jpg'
  },
  {
    id: 'the-man-from-u-n-c-l-e-2015',
    title: 'Агенты А.Н.К.Л.',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2015,
    genres: ['боевик', 'комедия', 'приключения'],
    rating: null,
    synopsis: 'В разгар Холодной войны агенты ЦРУ и КГБ вынуждены объединить усилия, чтобы остановить таинственную преступную организацию, стремящуюся завладеть ядерным оружием.',
    cover: 'images/covers/the-man-from-u-n-c-l-e-2015.jpg'
  },
  {
    id: 'eurotrip-2004',
    title: 'Евротур',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2004,
    genres: ['комедия', 'приключения'],
    rating: null,
    synopsis: 'Брошенный подругой выпускник школы отправляется вместе с друзьями в путешествие по Европе, чтобы найти немецкую переписчицу, в которую он неожиданно влюбился по интернету.',
    cover: 'images/covers/eurotrip-2004.jpg'
  },
  {
    id: 'the-hobbit-an-unexpected-journey-2012',
    title: 'Хоббит: Нежданное путешествие',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2012,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Хоббит Бильбо Бэггинс отправляется с волшебником Гэндальфом и отрядом из тринадцати гномов в опасное путешествие, чтобы отвоевать древнее королевство Эребор у дракона Смауга, — первый фильм трилогии-приквела «Властелина колец».',
    cover: 'images/covers/the-hobbit-an-unexpected-journey-2012.jpg'
  },
  {
    id: 'the-hobbit-the-desolation-of-smaug-2013',
    title: 'Хоббит: Пустошь Смауга',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2013,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Продолжая путь к Одинокой горе, Бильбо и гномы пересекают зачарованный лес Лихолесье, спасаются от эльфов и озёрных людей и наконец сталкиваются с драконом Смаугом, стерегущим украденные сокровища Эребора.',
    cover: 'images/covers/the-hobbit-the-desolation-of-smaug-2013.jpg'
  },
  {
    id: 'the-hobbit-the-battle-of-the-five-armies-2014',
    title: 'Хоббит: Битва пяти воинств',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2014,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Пробуждённый Смауг обрушивает свою ярость на Озёрный город, а вокруг обезлюдевшей горы Эребор сходятся армии людей, эльфов, гномов и орков в решающей битве за древнее королевство — финал трилогии.',
    cover: 'images/covers/the-hobbit-the-battle-of-the-five-armies-2014.png'
  },
  {
    id: 'drive-2011',
    title: 'Драйв',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2011,
    genres: ['криминал', 'драма', 'триллер'],
    rating: null,
    synopsis: 'Безымянный каскадёр и водитель на подработке ввязывается в ограбление, чтобы защитить соседку и её сына, и оказывается втянут в жестокое противостояние с криминальным миром Лос-Анджелеса.',
    cover: 'images/covers/drive-2011.jpg'
  },
  {
    id: 'the-batman-2022',
    title: 'Бэтмен',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2022,
    genres: ['боевик', 'детектив', 'триллер'],
    rating: null,
    synopsis: 'На втором году своей войны с преступностью Бэтмен расследует серию убийств, устроенных загадочным Риддлером, и раскрывает глубокую коррупцию, пронизывающую Готэм.',
    cover: 'images/covers/the-batman-2022.jpg'
  },
  {
    id: 'bullet-train-2022',
    title: 'Быстрее пули',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2022,
    genres: ['боевик', 'чёрная комедия', 'триллер'],
    rating: null,
    synopsis: 'Незадачливый наёмник по кличке Божья Коровка садится в скоростной японский поезд ради простого задания, но обнаруживает, что в вагонах едут ещё несколько убийц с пересекающимися и смертельно опасными миссиями.',
    cover: 'images/covers/bullet-train-2022.jpg'
  },
  {
    id: 'snatch-2000',
    title: 'Большой куш',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2000,
    genres: ['криминал', 'комедия', 'боевик'],
    rating: null,
    synopsis: 'Кража огромного бриллианта сталкивает лондонских бандитов, боксёров-нелегалов и цыганского боксёра по прозвищу Пуля в переплетении хаотичных и уморительных криминальных сюжетных линий.',
    cover: 'images/covers/snatch-2000.jpg'
  },
  {
    id: 'the-fountain-of-youth-2025',
    title: 'Источник вечной молодости',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['приключения', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Рассорившиеся брат и сестра объединяются в погоне за легендарным источником вечной молодости, спрятанным в череде опасных мест по всему миру.',
    cover: 'images/covers/the-fountain-of-youth-2025.jpg'
  },
  {
    id: 'jay-and-silent-bob-strike-back-2001',
    title: 'Джей и Молчаливый Боб наносят ответный удар',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2001,
    genres: ['комедия'],
    rating: null,
    synopsis: 'Узнав, что о них снимают фильм по комиксам без их разрешения и денег, Джей и Молчаливый Боб отправляются в Голливуд, чтобы сорвать съёмки, — комедийный привет всей киновселенной Кевина Смита.',
    cover: 'images/covers/jay-and-silent-bob-strike-back-2001.jpg'
  },
  {
    id: 'jay-and-silent-bob-reboot-2019',
    title: 'Джей и Молчаливый Боб: Перезагрузка',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2019,
    genres: ['комедия'],
    rating: null,
    synopsis: 'Узнав, что права на «Блантмена и Хроника» по решению суда достались голливудской студии, Джей и Молчаливый Боб снова мчатся через всю страну, чтобы сорвать съёмки перезапуска, — и по пути Джей неожиданно для себя знакомится с повзрослевшей дочерью.',
    cover: 'images/covers/jay-and-silent-bob-reboot-2019.jpg'
  },
  {
    id: 'masters-of-the-universe-2026',
    title: 'Властелины Вселенной',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Принц Адам возвращается на порабощённую Скелетором Этернию и должен принять свою судьбу, превратившись в Хи-Мэна, чтобы освободить родную планету, — игровая экранизация классической франшизы.',
    cover: 'images/covers/masters-of-the-universe-2026.jpg'
  },
  {
    id: 'the-village-2004',
    title: 'Таинственный лес',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2004,
    genres: ['триллер', 'драма', 'мистика'],
    rating: null,
    synopsis: 'Жители изолированной деревни XIX века живут в страхе перед существами, обитающими в окружающем лесу, но попытка одной из девушек покинуть поселение раскрывает мрачную тайну этого места.',
    cover: 'images/covers/the-village-2004.jpg'
  },
  {
    id: 'orphan-2009',
    title: 'Дитя тьмы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2009,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Супружеская пара, потерявшая ребёнка, удочеряет девочку из приюта, но вскоре начинает подозревать, что с новой дочерью и её прошлым связано нечто зловещее.',
    cover: 'images/covers/orphan-2009.jpg'
  },
  {
    id: 'case-39-2009',
    title: 'Дело №39',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2009,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Социальный работник забирает к себе домой девочку, которую, как ей кажется, жестоко истязают собственные родители, но вскоре понимает, что настоящая опасность исходит от самого ребёнка.',
    cover: 'images/covers/case-39-2009.jpg'
  },
  {
    id: 'house-at-the-end-of-the-street-2012',
    title: 'Дом в конце улицы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2012,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Мать с дочерью переезжают в дом по соседству с местом, где несколько лет назад произошло жуткое убийство, и вскоре девушка сближается с выжившим членом той семьи, скрывающим страшную тайну.',
    cover: 'images/covers/house-at-the-end-of-the-street-2012.jpg'
  },
  {
    id: 'the-skeleton-key-2005',
    title: 'Ключ от всех дверей',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2005,
    genres: ['ужасы', 'триллер', 'мистика'],
    rating: null,
    synopsis: 'Сиделка устраивается на работу в старинный особняк в Луизиане и, обнаружив мастер-ключ, открывающий все двери дома, погружается в тайны, связанные с практиками худу.',
    cover: 'images/covers/the-skeleton-key-2005.jpg'
  },
  {
    id: 'klaustrofoby-2019',
    title: 'Клаустрофобы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2019,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Шестеро незнакомцев получают таинственное приглашение принять участие в эскейп-руме, который оказывается смертельно опасной игрой на выживание, где любая ошибка стоит жизни.',
    cover: 'images/covers/klaustrofoby-2019.jpg'
  },
  {
    id: 'red-dragon-2002',
    title: 'Красный дракон',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2002,
    genres: ['триллер', 'криминал', 'ужасы'],
    rating: null,
    synopsis: 'Бывший агент ФБР Уилл Грэм, вышедший на пенсию после поимки Ганнибала Лектера, вынужден вновь обратиться за помощью к гениальному маньяку, чтобы выследить нового серийного убийцу по прозвищу Зубная Фея.',
    cover: 'images/covers/red-dragon-2002.jpg'
  },
  {
    id: 'hannibal-2001',
    title: 'Ганнибал',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2001,
    genres: ['триллер', 'криминал', 'ужасы'],
    rating: null,
    synopsis: 'Спустя десять лет после побега Ганнибал Лектер ведёт размеренную жизнь в Италии, пока агент ФБР Кларис Старлинг и жаждущий мести богач-инвалид не начинают на него охоту.',
    cover: 'images/covers/hannibal-2001.jpg'
  },
  {
    id: 'hannibal-rising-2007',
    title: 'Ганнибал: Восхождение',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2007,
    genres: ['триллер', 'драма', 'криминал'],
    rating: null,
    synopsis: 'История юного Ганнибала Лектера, потерявшего семью во время войны и вставшего на путь мести убийцам своей сестры, — приквел, объясняющий рождение знаменитого маньяка.',
    cover: 'images/covers/hannibal-rising-2007.jpg'
  },
  {
    id: 'the-big-lebowski-1998',
    title: 'Большой Лебовски',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1998,
    genres: ['комедия', 'криминал'],
    rating: null,
    synopsis: 'Лос-анджелесский лежебока по прозвищу Чувак становится жертвой ошибки, когда бандиты, перепутав его с богатым тёзкой, портят его любимый ковёр, — и втягивается в абсурдную историю с похищением и выкупом.',
    cover: 'images/covers/the-big-lebowski-1998.jpg'
  },
  {
    id: 'alien-1979',
    title: 'Чужой',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1979,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'Экипаж грузового космического корабля «Ностромо» сталкивается на удалённой планете со смертоносным инопланетным существом, которое проникает на борт и начинает охотиться на людей одного за другим.',
    cover: 'images/covers/alien-1979.jpg'
  },
  {
    id: 'aliens-1986',
    title: 'Чужие',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1986,
    genres: ['фантастика', 'ужасы', 'боевик'],
    rating: null,
    synopsis: 'Спустя десятилетия после гибели «Ностромо» Эллен Рипли возвращается на планету LV-426 вместе с отрядом космических пехотинцев, чтобы выяснить судьбу колонистов, — и обнаруживает, что чужие расплодились там в промышленных масштабах.',
    cover: 'images/covers/aliens-1986.jpg'
  },
  {
    id: 'alien-3-1992',
    title: 'Чужой 3',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1992,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'Спасательная капсула Рипли терпит крушение на отдалённой тюремной планете, населённой одними мужчинами, а вместе с ней на поверхность попадает и чужой, обрекающий обитателей колонии на новую кровавую охоту.',
    cover: 'images/covers/alien-3-1992.jpg'
  },
  {
    id: 'alien-resurrection-1997',
    title: 'Чужой 4: Воскрешение',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1997,
    genres: ['фантастика', 'ужасы', 'боевик'],
    rating: null,
    synopsis: 'Спустя двести лет после гибели Рипли учёные клонируют её, чтобы извлечь из тела ДНК инопланетной королевы, но эксперимент порождает новый гибридный вид чужих и заставляет саму Рипли усомниться в собственной человечности.',
    cover: 'images/covers/alien-resurrection-1997.jpg'
  },
  {
    id: 'prometheus-2012',
    title: 'Прометей',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2012,
    genres: ['фантастика', 'ужасы', 'приключения'],
    rating: null,
    synopsis: 'Экипаж исследовательского корабля «Прометей» отправляется к далёкой звёздной системе в поисках создателей человечества, но находит на чужой планете нечто куда более смертоносное, чем ответы на свои вопросы.',
    cover: 'images/covers/prometheus-2012.jpg'
  },
  {
    id: 'alien-covenant-2017',
    title: 'Чужой: Завет',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2017,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'Экипаж колонизационного корабля «Завет», перехватив загадочный сигнал с виду безопасной планеты, обнаруживает мир, где выжил лишь андроид Дэвид, — и попадает в ловушку древнего кошмара, положившего начало расе чужих.',
    cover: 'images/covers/alien-covenant-2017.jpg'
  },
  {
    id: 'alien-romulus-2024',
    title: 'Чужой: Ромул',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2024,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'Группа молодых колонистов пробирается на давно заброшенную космическую станцию в поисках ресурсов для побега с промышленной планеты, но обнаруживает, что станция кишит чужими, — события разворачиваются между первым и вторым фильмами саги.',
    cover: 'images/covers/alien-romulus-2024.jpg'
  },
  {
    id: 'alien-earth-2025',
    title: 'Чужой: Земля',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (2025, 8 серий)\nСезон 2 — подтверждён, съёмки идут в Лондоне (Pinewood Studios) с 2026 года; премьера ожидается не раньше 2027 года, точная дата пока не объявлена.',
    year: 2025,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'За несколько лет до событий оригинального «Чужого» на Земле терпит крушение исследовательский корабль с ксеноморфом и другими смертоносными формами жизни на борту — остановить их пытается отряд солдат корпорации «Продиджи» вместе с девушкой Венди, чьё сознание перенесено в тело синтетика.',
    cover: 'images/covers/alien-earth-2025.jpg',
    parts: [
      { name: 'Сезон 1', year: 2025, released: true },
      { name: 'Сезон 2', year: 2027, released: false }
    ]
  },
  {
    id: 'major-payne-1995',
    title: 'Майор Пэйн',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1995,
    genres: ['комедия', 'военный'],
    rating: null,
    synopsis: 'Уволенный из армии за чрезмерную жестокость майор устраивается инструктором в кадетскую школу и пытается воспитать из недисциплинированных подростков настоящих бойцов, попутно узнавая, что такое дружба и забота.',
    cover: 'images/covers/major-payne-1995.jpg'
  },
  {
    id: 'tucker-dale-vs-evil-2010',
    title: 'Убойные каникулы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2010,
    genres: ['комедия', 'ужасы'],
    rating: null,
    synopsis: 'Два добродушных, но неотёсанных приятеля отправляются на отдых в глухой лес, где компания студентов принимает их за маньяков-убийц, что приводит к цепи нелепых и кровавых недоразумений.',
    cover: 'images/covers/tucker-dale-vs-evil-2010.jpg'
  },
  {
    id: 'lilo-stitch-2025',
    title: 'Лило и Стич',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['фантастика', 'семейный', 'комедия'],
    rating: null,
    synopsis: 'Игровой ремейк классического мультфильма Disney: одинокая гавайская девочка Лило подружается с непослушным пришельцем Стичем, сбежавшим на Землю, и учит его, что значит быть частью настоящей семьи — «Оханы».',
    cover: 'images/covers/lilo-stitch-2025.jpg'
  },
  {
    id: 'baby-driver-2017',
    title: 'Малыш на драйве',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2017,
    genres: ['боевик', 'криминал', 'музыкальный'],
    rating: null,
    synopsis: 'Молодой талантливый водитель, работающий на криминального босса под звуки собственного плейлиста, пытается вырваться из преступного мира ради новой возлюбленной, но его втягивают в одно последнее опасное ограбление.',
    cover: 'images/covers/baby-driver-2017.jpg'
  },
  {
    id: 'split-fiction-2025',
    title: 'Split Fiction',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS5', 'Xbox Series X/S', 'Nintendo Switch 2'],
    year: 2025,
    genres: ['кооператив', 'приключение', 'экшен'],
    rating: null,
    synopsis: 'Две писательницы, Мио и Зои, попадают в ловушку внутри машины, похищающей творческие идеи, и вынуждены сообща пройти через миры их собственных научно-фантастических и фэнтезийных историй, чтобы найти выход.',
    cover: 'images/covers/split-fiction-2025.jpg'
  },
  {
    id: 'unravel-two-2018',
    title: 'Unravel Two',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch'],
    year: 2018,
    genres: ['кооператив', 'платформер', 'головоломка'],
    rating: null,
    synopsis: 'Два маленьких существа из пряжи, связанные общей нитью, оказываются выброшены на остров и учатся действовать сообща, преодолевая препятствия и головоломки в трогательной истории о дружбе и взаимовыручке.',
    cover: 'images/covers/unravel-two-2018.jpg'
  },
  {
    id: 'divinity-original-sin-2014',
    title: 'Divinity: Original Sin',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Mac', 'Linux', 'PS4', 'Xbox One'],
    year: 2014,
    genres: ['ролевая игра', 'пошаговая тактика'],
    rating: null,
    synopsis: 'Двое Охотников за Истоком расследуют убийство советника в городе Сайсил и постепенно раскрывают заговор, связанный с запретной магией Истока, сражаясь в пошаговых боях на изометрической карте мира Ривеллон.',
    cover: 'images/covers/divinity-original-sin-2014.jpg'
  },
  {
    id: 'divinity-original-sin-ii-2017',
    title: 'Divinity: Original Sin II',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Mac', 'PS4', 'Xbox One', 'Nintendo Switch', 'PS5', 'Xbox Series X/S', 'Nintendo Switch 2'],
    year: 2017,
    genres: ['ролевая игра', 'пошаговая тактика'],
    rating: null,
    synopsis: 'Изгои-Истокорожденные пытаются выжить в мире, охваченном нашествием Пустоты, создавая собственного героя или выбирая одного из персонажей с уникальной предысторией и путешествуя по Ривеллону в пошаговых тактических сражениях.',
    cover: 'images/covers/divinity-original-sin-ii-2017.jpg'
  },
  {
    id: 'iron-man-2008',
    title: 'Железный человек',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2008,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Миллиардер и оружейный магнат Тони Старк создаёт бронированный костюм, чтобы вырваться из плена, и превращает его в оружие для борьбы со злом, став супергероем Железным человеком.',
    cover: 'images/covers/iron-man-2008.jpg'
  },
  {
    id: 'the-incredible-hulk-2008',
    title: 'Невероятный Халк',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2008,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Учёный Брюс Бэннер скрывается от военных и пытается найти лекарство от гнева, превращающего его в гигантского зелёного монстра Халка, но армия хочет заполучить его силу как оружие.',
    cover: 'images/covers/the-incredible-hulk-2008.jpg'
  },
  {
    id: 'iron-man-2-2010',
    title: 'Железный человек 2',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2010,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Тони Старк, чья личность Железного человека стала достоянием общественности, борется с опасным побочным эффектом технологии, поддерживающей его жизнь, и новыми врагами, жаждущими заполучить его разработки.',
    cover: 'images/covers/iron-man-2-2010.jpg'
  },
  {
    id: 'thor-2011',
    title: 'Тор',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2011,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Высокомерный бог грома Тор изгнан отцом Одином на Землю и лишён своей силы; чтобы вернуть её и защитить оба мира от заговора, ему предстоит научиться быть достойным своего молота.',
    cover: 'images/covers/thor-2011.jpg'
  },
  {
    id: 'captain-america-the-first-avenger-2011',
    title: 'Первый мститель',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2011,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Слабый, но отважный Стив Роджерс становится суперсолдатом Капитаном Америкой и сражается с нацистской организацией ГИДРА во время Второй мировой войны.',
    cover: 'images/covers/captain-america-the-first-avenger-2011.jpg'
  },
  {
    id: 'the-avengers-2012',
    title: 'Мстители',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2012,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Когда Локи похищает Тессеракт и угрожает Земле армией читаури, Ник Фьюри собирает команду супергероев — Железного человека, Тора, Капитана Америку, Халка и других — чтобы остановить вторжение.',
    cover: 'images/covers/the-avengers-2012.jpg'
  },
  {
    id: 'iron-man-3-2013',
    title: 'Железный человек 3',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2013,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После разрушительной атаки террориста Мандарина и пережитых в Нью-Йорке потрясений Тони Старк, лишившийся дома и брони, должен рассчитывать только на собственную изобретательность, чтобы защитить близких.',
    cover: 'images/covers/iron-man-3-2013.jpg'
  },
  {
    id: 'thor-the-dark-world-2013',
    title: 'Тор 2: Царство тьмы',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2013,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Тор должен спасти Вселенную от древнего зла — тёмного эльфа Малекита, который стремится погрузить все девять миров во тьму с помощью могущественного оружия Эфира.',
    cover: 'images/covers/thor-the-dark-world-2013.jpg'
  },
  {
    id: 'captain-america-the-winter-soldier-2014',
    title: 'Первый мститель: Другая война',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Стив Роджерс обнаруживает, что организация Щ.И.Т. поражена изнутри Гидрой, и вынужден противостоять таинственному наёмному убийце по прозвищу Зимний солдат.',
    cover: 'images/covers/captain-america-the-winter-soldier-2014.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-2014',
    title: 'Стражи Галактики',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['фантастика', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Авантюрист Питер Квилл становится мишенью охотников за головами после кражи таинственной сферы и вынужден объединиться со странной компанией изгоев, чтобы спасти галактику.',
    cover: 'images/covers/guardians-of-the-galaxy-2014.jpg'
  },
  {
    id: 'avengers-age-of-ultron-2015',
    title: 'Мстители: Эра Альтрона',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2015,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Тони Старк создаёт искусственный интеллект Альтрона для защиты Земли, но программа выходит из-под контроля и решает, что для спасения планеты человечество нужно уничтожить.',
    cover: 'images/covers/avengers-age-of-ultron-2015.jpg'
  },
  {
    id: 'ant-man-2015',
    title: 'Человек-муравей',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2015,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Мелкий вор Скотт Лэнг получает от учёного Хэнка Пима костюм, позволяющий уменьшаться до размеров насекомого при сохранении силы удара, и должен использовать эту способность ради спасительного ограбления.',
    cover: 'images/covers/ant-man-2015.jpg'
  },
  {
    id: 'captain-america-civil-war-2016',
    title: 'Первый мститель: Противостояние',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2016,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Разногласия по поводу государственного контроля над супергероями раскалывают Мстителей на два враждующих лагеря во главе с Капитаном Америкой и Железным человеком.',
    cover: 'images/covers/captain-america-civil-war-2016.jpg'
  },
  {
    id: 'doctor-strange-2016',
    title: 'Доктор Стрэндж',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2016,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Блестящий, но самонадеянный нейрохирург Стивен Стрэндж после автокатастрофы, лишившей его рук, отправляется на поиски исцеления и открывает для себя мир магии и параллельных измерений.',
    cover: 'images/covers/doctor-strange-2016.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-vol-2-2017',
    title: 'Стражи Галактики. Часть 2',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['фантастика', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Стражи Галактики отправляются на поиски таинственного отца Питера Квилла и попутно защищают новообретённую семью от предательства и новых врагов.',
    cover: 'images/covers/guardians-of-the-galaxy-vol-2-2017.jpg'
  },
  {
    id: 'spider-man-homecoming-2017',
    title: 'Человек-паук: Возвращение домой',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Питер Паркер пытается совмещать школьную жизнь с обязанностями супергероя под присмотром Тони Старка, попутно раскрывая заговор торговца оружием Стервятника.',
    cover: 'images/covers/spider-man-homecoming-2017.jpg'
  },
  {
    id: 'thor-ragnarok-2017',
    title: 'Тор: Рагнарёк',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['фэнтези', 'супергероика', 'комедия'],
    rating: null,
    synopsis: 'Лишённый молота и заточённый на планете-свалке Сакааре, Тор должен успеть вернуться в Асгард и остановить свою сестру Хелу, богиню смерти, несущую Рагнарёк — конец света.',
    cover: 'images/covers/thor-ragnarok-2017.jpg'
  },
  {
    id: 'black-panther-2018',
    title: 'Чёрная пантера',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После смерти отца Т’Чалла возвращается в технологически передовое африканское королевство Ваканда, чтобы занять трон, но сталкивается с претендентом, ставящим под угрозу судьбу страны и всего мира.',
    cover: 'images/covers/black-panther-2018.jpg'
  },
  {
    id: 'avengers-infinity-war-2018',
    title: 'Мстители: Война бесконечности',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Мстители и их союзники объединяются, чтобы остановить безумного титана Таноса, собирающего Камни Бесконечности ради уничтожения половины всего живого во Вселенной.',
    cover: 'images/covers/avengers-infinity-war-2018.jpg'
  },
  {
    id: 'ant-man-and-the-wasp-2018',
    title: 'Человек-муравей и Оса',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Скотт Лэнг вновь надевает костюм Человека-муравья и объединяется с Хоуп ван Дайн, ставшей Осой, чтобы спасти её мать из Квантовой сферы, где она пропала много лет назад.',
    cover: 'images/covers/ant-man-and-the-wasp-2018.jpg'
  },
  {
    id: 'captain-marvel-2019',
    title: 'Капитан Марвел',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Пилот военно-космических сил Кри Вирс Данверс, обретя сверхспособности, оказывается в центре межгалактического конфликта и постепенно вспоминает своё прошлое на Земле.',
    cover: 'images/covers/captain-marvel-2019.jpg'
  },
  {
    id: 'avengers-endgame-2019',
    title: 'Мстители: Финал',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После уничтожения половины Вселенной оставшиеся Мстители разрабатывают отчаянный план с использованием путешествий во времени, чтобы отменить деяния Таноса и вернуть погибших.',
    cover: 'images/covers/avengers-endgame-2019.jpg'
  },
  {
    id: 'spider-man-far-from-home-2019',
    title: 'Человек-паук: Вдали от дома',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер отправляется на каникулы в Европу, но вынужден вернуться к обязанностям супергероя, когда Ник Фьюри просит его помочь остановить нападения загадочных существ из стихий.',
    cover: 'images/covers/spider-man-far-from-home-2019.jpg'
  },
  {
    id: 'black-widow-2021',
    title: 'Чёрная вдова',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Наташа Романофф сталкивается с тёмным прошлым, когда всплывает опасная заговорщическая организация, связывающая её с семьёй шпионов, вырастившей её, и требующая закрыть счёты.',
    cover: 'images/covers/black-widow-2021.jpg'
  },
  {
    id: 'shang-chi-and-the-legend-of-the-ten-rings-2021',
    title: 'Шан-Чи и легенда десяти колец',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Шан-Чи, мастер боевых искусств, скрывающийся от прошлого, вынужден противостоять своему отцу — лидеру тайной организации, владеющему десятью кольцами безграничной силы.',
    cover: 'images/covers/shang-chi-and-the-legend-of-the-ten-rings-2021.jpg'
  },
  {
    id: 'eternals-2021',
    title: 'Вечные',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'фантастика', 'фэнтези'],
    rating: null,
    synopsis: 'Раскрытые бессмертные существа, тысячелетиями тайно жившие среди людей, вынуждены вновь объединиться, чтобы защитить человечество от древних чудовищ Девиантов.',
    cover: 'images/covers/eternals-2021.jpg'
  },
  {
    id: 'spider-man-no-way-home-2021',
    title: 'Человек-паук: Нет пути домой',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'После раскрытия личности Человека-паука Питер Паркер просит Доктора Стрэнджа стереть эту тайну из памяти людей, но неудачное заклинание открывает мультивселенную и впускает опасных врагов из других реальностей.',
    cover: 'images/covers/spider-man-no-way-home-2021.jpg'
  },
  {
    id: 'doctor-strange-in-the-multiverse-of-madness-2022',
    title: 'Доктор Стрэндж: В мультивселенной безумия',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['фэнтези', 'супергероика', 'ужасы'],
    rating: null,
    synopsis: 'Доктор Стрэндж вместе с юной Америкой Чавес, способной путешествовать между вселенными, отправляется в опасное путешествие по мультивселенной, спасаясь от могущественного врага, охотящегося за её силой.',
    cover: 'images/covers/doctor-strange-in-the-multiverse-of-madness-2022.jpg'
  },
  {
    id: 'thor-love-and-thunder-2022',
    title: 'Тор: Любовь и гром',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['фэнтези', 'супергероика', 'комедия'],
    rating: null,
    synopsis: 'Тор пытается обрести внутренний покой, но вынужден вернуться в бой, когда Голод Богов начинает истреблять богов по всей Вселенной, а его бывшая возлюбленная Джейн Фостер обретает силу Тора.',
    cover: 'images/covers/thor-love-and-thunder-2022.jpg'
  },
  {
    id: 'black-panther-wakanda-forever-2022',
    title: 'Чёрная Пантера: Ваканда навсегда',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['супергероика', 'боевик', 'драма'],
    rating: null,
    synopsis: 'После смерти короля Т’Чаллы королева Рамонда и защитники Ваканды должны отстоять независимость страны от новых угроз, включая подводное королевство Талокан во главе с Нэмором.',
    cover: 'images/covers/black-panther-wakanda-forever-2022.jpg'
  },
  {
    id: 'ant-man-and-the-wasp-quantumania-2023',
    title: 'Человек-муравей и Оса: Квантомания',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Семья Лэнг случайно оказывается заброшена в Квантовую сферу, где сталкивается с могущественным завоевателем Кэнгом, чьи планы угрожают не только их миру, но и всей мультивселенной.',
    cover: 'images/covers/ant-man-and-the-wasp-quantumania-2023.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-vol-3-2023',
    title: 'Стражи Галактики. Часть 3',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['фантастика', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Стражи Галактики отправляются в опасную миссию, чтобы спасти жизнь Ракеты, и попутно раскрывают тёмную историю его создания корпорацией «Верховная эволюция».',
    cover: 'images/covers/guardians-of-the-galaxy-vol-3-2023.jpg'
  },
  {
    id: 'the-marvels-2023',
    title: 'Марвелы',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Капитан Марвел, Мисс Марвел и Моника Рэмбо случайно меняются местами каждый раз при использовании своих сил и вынуждены объединиться, чтобы вместе остановить новую угрозу галактике.',
    cover: 'images/covers/the-marvels-2023.jpg'
  },
  {
    id: 'deadpool-wolverine-2024',
    title: 'Дэдпул и Росомаха',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2024,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Уэйд Уилсон попадает в поле зрения Управления временными изменениями и вынужден уговорить недовольного жизнью Росомаху помочь ему спасти собственную реальность от уничтожения.',
    cover: 'images/covers/deadpool-wolverine-2024.jpg'
  },
  {
    id: 'captain-america-brave-new-world-2025',
    title: 'Капитан Америка: Новый мир',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Новый Капитан Америка Сэм Уилсон оказывается втянут в международный заговор, когда покушение на президента США заставляет его выяснить, кто пытается разжечь мировую войну.',
    cover: 'images/covers/captain-america-brave-new-world-2025.jpg'
  },
  {
    id: 'thunderbolts-2025',
    title: 'Громовержцы*',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Группа бывших наёмников, шпионов и антигероев, преданных собственным правительством, вынуждена объединиться в опасную команду, чтобы выжить и раскрыть тёмную тайну.',
    cover: 'images/covers/thunderbolts-2025.jpg'
  },
  {
    id: 'the-fantastic-four-first-steps-2025',
    title: 'Фантастическая четвёрка: Первые шаги',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'В ретрофутуристическом 1960-х Реед Ричардс, Сью Шторм, Джонни Шторм и Бен Гримм, обретшие сверхспособности после космической экспедиции, должны защитить Землю от пожирателя планет Галактуса.',
    cover: 'images/covers/the-fantastic-four-first-steps-2025.jpg'
  },
  {
    id: 'spider-man-brand-new-day-2026',
    title: 'Человек-паук: Новый день',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2026,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'После событий «Нет пути домой» Питер Паркер, забытый всем миром, пытается заново выстроить жизнь и отношения, оставаясь Человеком-пауком и сталкиваясь с новыми врагами.',
    cover: 'images/covers/spider-man-brand-new-day-2026.jpg'
  },
  {
    id: 'avengers-doomsday-2026',
    title: 'Мстители: Судный день',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Герои из трёх разных вселенных оказываются на пути столкновения с небывалой угрозой в лице Виктора фон Дума — в этой роли на экран возвращается Роберт Дауни-младший, ранее игравший Тони Старка.',
    cover: 'images/covers/avengers-doomsday-2026.jpg'
  },
  {
    id: 'avengers-secret-wars-2027',
    title: 'Мстители: Секретные войны',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2027,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Финал Саги Мультивселенной: герои и злодеи Marvel сходятся в решающей битве с Доктором Думом на арене, вдохновлённой комиксовым Battleworld, — режиссёры Энтони и Джо Руссо завершают историю, начатую в «Судном дне».',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'x-men-2028',
    title: 'Люди Икс',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Перезапуск истории о мутантах внутри MCU после событий «Секретных войн»: новый актёрский состав во главе с Джин Грей и Циклопом, представленный режиссёром Джейком Шрайером.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'ghost-rider-2028',
    title: 'Призрачный гонщик',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'мистика'],
    rating: null,
    synopsis: 'Джонни Блейз заключает сделку с дьяволом и становится Призрачным гонщиком — байкером-мстителем с горящим черепом — в отдельном фильме Marvel Studios с Райаном Гослингом в главной роли, режиссёр Шон Леви.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'black-panther-iii-2028',
    title: 'Чёрная пантера 3',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'драма'],
    rating: null,
    synopsis: 'Повзрослевший сын Т’Чаллы принимает мантию Чёрной пантеры и наследие Ваканды — третий фильм франшизы Райана Куглера, с Дэвидом Джонссоном в главной роли.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'wandavision-2021',
    title: 'Ванда/Вижн',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2021, 9 серий), законченный минисериал; история продолжилась в спин-оффах «Это всё Агата» и «Квест Вижна».',
    year: 2021,
    genres: ['супергероика', 'драма', 'мистика'],
    rating: null,
    synopsis: 'Ванда Максимофф и Вижн живут идиллической жизнью в пригороде, где реальность подозрительно напоминает классические американские ситкомы разных десятилетий, — но за фасадом благополучия скрывается куда более мрачная тайна.',
    cover: 'images/covers/wandavision-2021.webp'
  },
  {
    id: 'the-falcon-and-the-winter-soldier-2021',
    title: 'Сокол и Зимний солдат',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2021, 6 серий), законченный минисериал; сюжет продолжился в фильме «Капитан Америка: Новый мир».',
    year: 2021,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Сэм Уилсон и Баки Барнс объединяются, чтобы остановить группировку «Флаг-крушители» и разобраться с наследием щита Капитана Америка, оставшегося без хозяина.',
    cover: 'images/covers/the-falcon-and-the-winter-soldier-2021.webp'
  },
  {
    id: 'loki-2021',
    title: 'Локи',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '2 сезона (2021, 2023), история завершена; третий сезон официально не анонсирован, хотя герой появится в третьем сезоне «Что, если...?».',
    year: 2021,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'Похищенный после кражи Тессеракта бог обмана попадает в Управление временными изменениями, где вынужден помогать в охоте на опасный вариант самого себя, распутывая заговор вокруг Священной временной линии.',
    cover: 'images/covers/loki-2021.webp'
  },
  {
    id: 'what-if-2021',
    title: 'Что, если...?',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '3 сезона (2021, 2023, 2024), сериал завершён — Marvel объявила третий сезон финальным.',
    year: 2021,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'Анимационная антология альтернативных вселенных Marvel: всевидящий Наблюдатель проводит зрителя через сценарии, в которых знаковые события киновселенной пошли по другому пути.',
    cover: 'images/covers/what-if-2021.webp'
  },
  {
    id: 'hawkeye-2021',
    title: 'Соколиный глаз',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2021, 6 серий), законченный минисериал; линия Кейт Бишоп продолжилась в спин-оффе «Эхо».',
    year: 2021,
    genres: ['супергероика', 'боевик', 'детектив'],
    rating: null,
    synopsis: 'Клинт Бартон готовится вернуться домой на Рождество, но оказывается втянут в криминальные разборки Нью-Йорка вместе с начинающей лучницей Кейт Бишоп, которая мечтает стать супергероем.',
    cover: 'images/covers/hawkeye-2021.webp'
  },
  {
    id: 'moon-knight-2022',
    title: 'Лунный рыцарь',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2022, 6 серий), законченный минисериал; второй сезон не подтверждён — Marvel планирует вернуть героя в других проектах.',
    year: 2022,
    genres: ['супергероика', 'мистика', 'триллер'],
    rating: null,
    synopsis: 'Тихий работник музейного магазина Стивен Грант обнаруживает, что делит тело и сознание с наёмником Марком Спектором — аватаром древнего египетского бога луны Хонсу.',
    cover: 'images/covers/moon-knight-2022.webp'
  },
  {
    id: 'ms-marvel-2022',
    title: 'Мисс Марвел',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2022, 6 серий), законченный минисериал; история Камалы Хан продолжилась в фильме «Марвелы».',
    year: 2022,
    genres: ['супергероика', 'комедия', 'фэнтези'],
    rating: null,
    synopsis: 'Американка пакистанского происхождения Камала Хан, фанатка Капитана Марвел, неожиданно обретает собственные суперспособности и берёт имя Мисс Марвел, защищая родной Джерси-Сити.',
    cover: 'images/covers/ms-marvel-2022.webp'
  },
  {
    id: 'she-hulk-attorney-at-law-2022',
    title: 'Женщина-Халк: Адвокат',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2022, 9 серий), законченный минисериал; продолжение не анонсировано.',
    year: 2022,
    genres: ['супергероика', 'комедия', 'драма'],
    rating: null,
    synopsis: 'Адвокат Дженнифер Уолтерс получает силы Халка от кузена Брюса Беннера и пытается совмещать юридическую карьеру с жизнью зелёной супергероини.',
    cover: 'images/covers/she-hulk-attorney-at-law-2022.webp'
  },
  {
    id: 'i-am-groot-2022',
    title: 'Я есть Грут',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '2 сезона коротких серий (2022, 2023, по 5 эпизодов); третий сезон обсуждается создателями, но официально не подтверждён.',
    year: 2022,
    genres: ['приключения', 'комедия', 'семейный'],
    rating: null,
    synopsis: 'Серия короткометражек о взрослении малыша Грута в галактике: маленький герой постоянно попадает в забавные передряги вместе со странными существами, которых встречает по пути.',
    cover: 'images/covers/i-am-groot-2022.webp'
  },
  {
    id: 'secret-invasion-2023',
    title: 'Секретное вторжение',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2023, 6 серий), законченный минисериал; продолжение не анонсировано.',
    year: 2023,
    genres: ['супергероика', 'триллер', 'боевик'],
    rating: null,
    synopsis: 'Ник Фьюри узнаёт о десятилетиями готовившемся вторжении скруллов-оборотней на Землю и вместе с союзниками пытается предотвратить войну, в которой невозможно понять, кому доверять.',
    cover: 'images/covers/secret-invasion-2023.webp'
  },
  {
    id: 'echo-2024',
    title: 'Эхо',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2024, 5 серий), законченный минисериал под брендом Marvel Spotlight; продолжение не анонсировано.',
    year: 2024,
    genres: ['драма', 'боевик', 'криминал'],
    rating: null,
    synopsis: 'Глухая преступница из народа шайенов Майя Лопес возвращается на родину, спасаясь от гнева Кингпина, и заново открывает связь со своими корнями и семьёй.',
    cover: 'images/covers/echo-2024.webp'
  },
  {
    id: 'agatha-all-along-2024',
    title: 'Это всё Агата',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2024, 9 серий), законченный минисериал; второй сезон не планируется — история задумывалась как разовая, как и «Ванда/Вижн».',
    year: 2024,
    genres: ['мистика', 'комедия', 'драма'],
    rating: null,
    synopsis: 'Могущественная ведьма Агата Харкнесс, лишённая магии после событий «Ванда/Вижн», собирает разношёрстный ковен и отправляется по Дороге ведьм, чтобы вернуть себе силу.',
    cover: 'images/covers/agatha-all-along-2024.webp'
  },
  {
    id: 'your-friendly-neighborhood-spider-man-2025',
    title: 'Ваш дружелюбный сосед Человек-паук',
    category: 'series',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (январь 2025)\nСезон 2 — перенесён на январь 2027 года (шоу продлено минимум на три сезона).',
    year: 2025,
    genres: ['супергероика', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Молодой Питер Паркер делает первые шаги в роли Человека-паука в альтернативной реальности, где его наставником становится не Тони Старк, а Норман Озборн.',
    cover: 'images/covers/your-friendly-neighborhood-spider-man-2025.webp'
  },
  {
    id: 'daredevil-born-again-2025',
    title: 'Сорвиголова: Рождённый заново',
    category: 'series',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '2 сезона (2025; 2026, финал в мае)\nСезон 3 — премьера ожидается в марте 2027 года.',
    year: 2025,
    genres: ['криминал', 'драма', 'боевик'],
    rating: null,
    synopsis: 'Мэтт Мёрдок пытается оставить прошлое супергероя позади и вернуться к юридической практике, но возвращение Уилсона Фиска — на этот раз в кресле мэра Нью-Йорка — заставляет его снова надеть маску Сорвиголовы.',
    cover: 'images/covers/daredevil-born-again-2025.webp'
  },
  {
    id: 'ironheart-2025',
    title: 'Железное сердце',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2025, 6 серий), законченный минисериал; второй сезон не подтверждён и не отменён — будущее неясно.',
    year: 2025,
    genres: ['супергероика', 'фантастика', 'мистика'],
    rating: null,
    synopsis: 'Юная гениальная изобретательница Рири Уильямс возвращается в родной Чикаго с собственным доспехом в стиле Железного человека и сталкивается с таинственным преступником по прозвищу Капюшон.',
    cover: 'images/covers/ironheart-2025.webp'
  },
  {
    id: 'eyes-of-wakanda-2025',
    title: 'Очи Ваканды',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (2025, 4 серии), законченная антология; продолжение официально не подтверждено, но создатели его не исключают.',
    year: 2025,
    genres: ['приключения', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Антология о тайных воинах Хатут Заразе, которые на протяжении веков покидали границы Ваканды, чтобы вернуть утраченные артефакты из вибраниума.',
    cover: 'images/covers/eyes-of-wakanda-2025.webp'
  },
  {
    id: 'marvel-zombies-2025',
    title: 'Зомби Marvel',
    category: 'series',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (октябрь 2025, 4 серии)\nСезон 2 — премьера ожидается не раньше 2027–2028 года.',
    year: 2025,
    genres: ['ужасы', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'В мире, охваченном зомби-эпидемией, уцелевшие герои — Камала Хан, Рири Уильямс, Кейт Бишоп и другие — объединяются в отряд, чтобы выжить среди бывших союзников, утративших человечность.',
    cover: 'images/covers/marvel-zombies-2025.webp'
  },
  {
    id: 'wonder-man-2026',
    title: 'Чудо-человек',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: '1 сезон (январь 2026, 8 серий); несмотря на изначальное продление, в июле 2026 года Disney+ отменил сериал.',
    year: 2026,
    genres: ['комедия', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Начинающий актёр и бывший супергерой Саймон Уильямс пытается пробиться в Голливуде и получает роль в экранизации собственной супергеройской биографии — с неожиданными последствиями для реальной жизни.',
    cover: 'images/covers/wonder-man-2026.webp'
  },
  {
    id: 'visionquest-2026',
    title: 'Квест Вижна',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Премьера минисериала (8 серий) — 14 октября 2026 года, заключительная часть трилогии «Ванда/Вижн»; продолжение не анонсировано.',
    year: 2026,
    genres: ['фантастика', 'драма', 'боевик'],
    rating: null,
    synopsis: 'Вижн, лишённый эмоций после потери воспоминаний, отправляется на поиски себя и своего места в мире — заключительная часть трилогии, начатой сериалом «Ванда/Вижн».',
    cover: 'images/covers/visionquest-2026.webp'
  },
  {
    id: 'lanterns-2026',
    title: 'Фонари',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: '1 сезон (премьера 16 августа 2026 года, 8 серий выходят еженедельно по воскресеньям до 4 октября 2026 года).',
    year: 2026,
    genres: ['супергероика', 'детектив', 'фантастика'],
    rating: null,
    synopsis: 'Ветеран Корпуса Зелёных Фонарей Хэл Джордан и новобранец Джон Стюарт — два галактических полицейских — расследуют убийство в глубинке Небраски, и рутинное дело оборачивается заговором, угрожающим всей планете.',
    cover: 'images/covers/lanterns-2026.jpg'
  },
  {
    id: 'supergerl-2026',
    title: 'Супергёрл',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'В свой двадцать первый день рождения Кара Зор-Эл — двоюродная сестра Супермена, выросшая на обломках Криптона, — путешествует по галактике вместе с суперпсом Крипто. Встреча с юной Рути Мэй Нолл втягивает её в опасную погоню за безжалостным пиратом, убившим семью девочки, и заставляет по-новому взглянуть на грань между героизмом и местью.',
    cover: 'images/covers/supergerl-2026.jpg'
  },
  {
    id: 'a-way-out-2018',
    title: 'A Way Out',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'Xbox One'],
    year: 2018,
    genres: ['кооператив', 'экшен', 'приключения'],
    rating: null,
    synopsis: 'Два заключённых, Лео и Винсент, планируют дерзкий побег из тюрьмы и месть тем, кто их подставил, — история, рассчитанная исключительно на кооперативное прохождение вдвоём, без возможности игры в одиночку.',
    cover: 'images/covers/a-way-out-2018.jpg'
  },
  {
    id: 'bokura-2023',
    title: 'Bokura',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Nintendo Switch', 'iOS', 'Android'],
    year: 2023,
    genres: ['кооператив', 'головоломка', 'приключения'],
    rating: null,
    synopsis: 'Два мальчика сбегают из дома и отправляются в путешествие через таинственный мир, который каждый из игроков видит по-своему, — кооперативная головоломка о дружбе, где решение задач требует постоянного общения и доверия напарнику.',
    cover: 'images/covers/bokura-2023.jpg'
  },
  {
    id: 'directive-8020-2026',
    title: 'Directive 8020',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS5', 'Xbox Series X/S'],
    year: 2026,
    genres: ['хоррор', 'фантастика', 'интерактивное кино'],
    rating: null,
    synopsis: 'Пятая часть серии The Dark Pictures и первая игра её второго сезона: экипаж колонизационного корабля «Кассиопея» терпит крушение на далёкой планете Тау Кита f и сталкивается с ксенофобным инопланетным организмом — фантастический хоррор с элементами боди-хоррора и кооперативным режимом на пятерых.',
    cover: 'images/covers/directive-8020-2026.jpg'
  },
  {
    id: 'escape-simulator-2-2025',
    title: 'Escape Simulator 2',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC'],
    year: 2025,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Продолжение популярного симулятора квестов-побегов: игроки в одиночку или совместно (до восьми человек онлайн) решают головоломки в разнообразных тематических комнатах, а также могут создавать и публиковать собственные испытания.',
    cover: 'images/covers/escape-simulator-2-2025.jpg'
  },
  {
    id: 'haven-2020',
    title: 'Haven',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2020,
    genres: ['ролевая игра', 'приключения', 'кооператив'],
    rating: null,
    synopsis: 'Влюблённая пара, Ю и Кей, сбегает от общества на заброшенную планету, чтобы быть вместе, — атмосферная ролевая игра о свободе и отношениях, которую можно проходить в одиночку или вдвоём за одним экраном.',
    cover: 'images/covers/haven-2020.jpg'
  },
  {
    id: 'nobody-saves-the-world-2022',
    title: 'Nobody Saves the World',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2022,
    genres: ['ролевая игра', 'экшен', 'кооператив'],
    rating: null,
    synopsis: 'Безликий герой по прозвищу Никто получает Волшебную Палочку и способность превращаться в десятки разных существ — от слизня до дракона, — чтобы остановить нашествие тьмы; игру можно проходить в одиночку или в кооперативе с другом.',
    cover: 'images/covers/nobody-saves-the-world-2022.jpg'
  },
  {
    id: 'operation-tango-2021',
    title: 'Operation: Tango',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2021,
    genres: ['кооператив', 'экшен', 'приключения'],
    rating: null,
    synopsis: 'Асимметричный шпионский боевик для двоих: один игрок управляет полевым агентом, другой — хакером, удалённо взламывающим системы, и только слаженная совместная работа помогает предотвратить международный заговор.',
    cover: 'images/covers/operation-tango-2021.jpg'
  },
  {
    id: 'orbitals-2026',
    title: 'Orbitals',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['Nintendo Switch 2'],
    year: 2026,
    genres: ['кооператив', 'головоломка', 'приключения'],
    rating: null,
    synopsis: 'Эксклюзив для Nintendo Switch 2 в стилистике ретро-аниме 90-х: два друга, Маки и Омура, выросшие на разрушающейся космической станции, отправляются в путешествие сквозь загадочный космический шторм, чтобы спасти свой дом, — игра рассчитана только на совместное прохождение вдвоём.',
    cover: 'images/covers/orbitals-2026.jpg'
  },
  {
    id: 'portal-2-2011',
    title: 'Portal 2',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Mac', 'Linux', 'PS3', 'Xbox 360'],
    year: 2011,
    genres: ['головоломка', 'шутер', 'научная фантастика'],
    rating: null,
    synopsis: 'Продолжение культовой головоломки от первого лица: Челл вновь просыпается в заброшенном комплексе Aperture Science, чтобы противостоять безумному ИИ ГЛаДОС, — включает полноценную кооперативную кампанию для двух роботов-андроидов.',
    cover: 'images/covers/portal-2-2011.jpg'
  },
  {
    id: 'rayman-legends-retold-2026',
    title: 'Rayman Legends Retold',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS5', 'Xbox Series X/S', 'Nintendo Switch 2'],
    year: 2026,
    genres: ['платформер', 'кооператив', 'приключения'],
    rating: null,
    synopsis: 'Переосмысленная версия Rayman Legends (2013) на движке Snowdrop с новой 3D-графикой: Рэйман, Глоуокс и их друзья вновь спасают Мир Снов от кошмаров — с новыми уровнями, музыкальными этапами и локальным кооперативом на четверых.',
    cover: 'images/covers/rayman-legends-retold-2026.jpg'
  },
  {
    id: 'spiritfarer-farewell-edition-2021',
    title: 'Spiritfarer: Farewell Edition',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch'],
    year: 2021,
    genres: ['симулятор', 'приключения', 'кооператив'],
    rating: null,
    synopsis: 'Расширенное издание уютного менеджмент-симулятора о смерти: Стелла становится паромщицей духов и, путешествуя на собственном корабле, заботится о своих пассажирах перед тем, как проводить их в загробный мир; издание объединяет базовую игру со всем вышедшим дополнительным контентом и поддерживает локальный кооператив.',
    cover: 'images/covers/spiritfarer-farewell-edition-2021.jpg'
  },
  {
    id: 'stardew-valley-2016',
    title: 'Stardew Valley',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'Mac', 'Linux', 'PS4', 'Xbox One', 'Nintendo Switch', 'iOS', 'Android'],
    year: 2016,
    genres: ['симулятор', 'ролевая игра', 'кооператив'],
    rating: null,
    synopsis: 'Унаследовав от деда старую ферму, герой уезжает из города, чтобы возродить заброшенные угодья, — фермерский симулятор с элементами ролевой игры, рыбалкой, шахтами и социальными связями с жителями деревни; поддерживает совместную игру до четырёх человек.',
    cover: 'images/covers/stardew-valley-2016.jpg'
  },
  {
    id: 'the-dark-pictures-anthology-man-of-medan-2019',
    title: 'The Dark Pictures Anthology: Man of Medan',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2019,
    genres: ['хоррор', 'интерактивное кино'],
    rating: null,
    synopsis: 'Первая часть антологии The Dark Pictures: группа друзей отправляется на дайвинг к затонувшему кораблю Второй мировой войны и оказывается на заброшенном судне-призраке — интерактивный хоррор, где решения игроков определяют, кто из героев доживёт до финала.',
    cover: 'images/covers/the-dark-pictures-anthology-man-of-medan-2019.jpg'
  },
  {
    id: 'the-dark-pictures-anthology-little-hope-2020',
    title: 'The Dark Pictures Anthology: Little Hope',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2020,
    genres: ['хоррор', 'интерактивное кино'],
    rating: null,
    synopsis: 'Вторая часть антологии The Dark Pictures: после поломки автобуса группа студентов и их преподаватель застревают в заброшенном городке Литтл-Хоуп, где их преследуют призраки, связанные с трагедией времён охоты на ведьм.',
    cover: 'images/covers/the-dark-pictures-anthology-little-hope-2020.jpg'
  },
  {
    id: 'the-dark-pictures-anthology-house-of-ashes-2021',
    title: 'The Dark Pictures Anthology: House of Ashes',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S'],
    year: 2021,
    genres: ['хоррор', 'интерактивное кино'],
    rating: null,
    synopsis: 'Третья часть антологии The Dark Pictures: отряд американских солдат и иракских бойцов проваливается в подземный шумерский храм во время военной операции 2003 года и обнаруживает там древних существ, ради выживания которых враждующим сторонам приходится объединиться.',
    cover: 'images/covers/the-dark-pictures-anthology-house-of-ashes-2021.jpg'
  },
  {
    id: 'the-dark-pictures-anthology-the-devil-in-me-2022',
    title: 'The Dark Pictures Anthology: The Devil in Me',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S'],
    year: 2022,
    genres: ['хоррор', 'интерактивное кино'],
    rating: null,
    synopsis: 'Четвёртая часть антологии The Dark Pictures: съёмочная группа документального фильма о маньяках получает приглашение в точную копию «Отеля-убийцы» Германа Маджетта и оказывается в ловушке безумного коллекционера, вдохновлённого настоящим серийным убийцей.',
    cover: 'images/covers/the-dark-pictures-anthology-the-devil-in-me-2022.jpg'
  },
  {
    id: 'the-dark-pictures-switchback-vr-2023',
    title: 'The Dark Pictures: Switchback VR',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PS VR2'],
    year: 2023,
    genres: ['хоррор', 'шутер', 'VR'],
    rating: null,
    synopsis: 'VR-рельсовый шутер по мотивам вселенной The Dark Pictures: игрок отстреливается от монстров и маньяков из первых четырёх игр антологии, проезжая через жуткие декорации на вагонетке, — динамичный спин-офф специально для PlayStation VR2.',
    cover: 'images/covers/the-dark-pictures-switchback-vr-2023.jpg'
  },
  {
    id: 'trine-4-the-nightmare-prince-2019',
    title: 'Trine 4: The Nightmare Prince',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'Xbox One', 'Nintendo Switch'],
    year: 2019,
    genres: ['платформер', 'головоломка', 'кооператив'],
    rating: null,
    synopsis: 'Воин Понтий, воровка Зойя и волшебница Амадея вновь объединяются, чтобы остановить принца Селиуса, чьи кошмары вырываются в реальный мир, — сказочный кооперативный платформер с физическими головоломками для одного—четырёх игроков.',
    cover: 'images/covers/trine-4-the-nightmare-prince-2019.jpg'
  },
  {
    id: 'trine-5-a-clockwork-conspiracy-2023',
    title: 'Trine 5: A Clockwork Conspiracy',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2023,
    genres: ['платформер', 'головоломка', 'кооператив'],
    rating: null,
    synopsis: 'Пятая часть сказочной серии: троица героев отправляется в королевство, захваченное часовым механизмом безумной королевы, чтобы вернуть магии и жителям королевства свободу, — вновь сочетает платформинг, физические головоломки и кооператив на четверых.',
    cover: 'images/covers/trine-5-a-clockwork-conspiracy-2023.jpg'
  },
  {
    id: 'we-were-here-2017',
    title: 'We Were Here',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2017,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Первая игра серии: два игрока, разлучённые в заброшенном замке среди льдов, должны провести друг друга через ловушки и головоломки, полагаясь только на голосовую связь по рации, — бесплатная кооперативная игра-побег, положившая начало серии.',
    cover: 'images/covers/we-were-here-2017.jpg'
  },
  {
    id: 'we-were-here-too-2018',
    title: 'We Were Here Too',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2018,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Продолжение асимметричной кооперативной головоломки: два игрока вновь оказываются разделены внутри замка и должны решать всё более сложные загадки, общаясь только по рации и полагаясь на описание того, что видит напарник.',
    cover: 'images/covers/we-were-here-too-2018.jpg'
  },
  {
    id: 'we-were-here-together-2019',
    title: 'We Were Here Together',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch'],
    year: 2019,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Третья часть серии: экспедиция в ледяной Антарктике оборачивается катастрофой, и два выживших должны преодолеть замёрзший комплекс, полный головоломок, полагаясь исключительно на общение по рации, чтобы найти друг друга.',
    cover: 'images/covers/we-were-here-together-2019.jpg'
  },
  {
    id: 'we-were-here-forever-2022',
    title: 'We Were Here Forever',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S'],
    year: 2022,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Четвёртая полноценная часть серии: два узника пытаются сбежать из мрачного замка-тюрьмы Кастилья, решая самые масштабные и разнообразные головоломки серии — от механических устройств до полноценного театрального представления, — общаясь только по рации.',
    cover: 'images/covers/we-were-here-forever-2022.jpg'
  },
  {
    id: 'we-were-here-expeditions-the-friendship-2023',
    title: 'We Were Here Expeditions: The FriendShip',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    platforms: ['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X/S'],
    year: 2023,
    genres: ['кооператив', 'головоломка', 'квест'],
    rating: null,
    synopsis: 'Пятая игра серии и первая в подсерии Expeditions: два матроса разбираются с последствиями кораблекрушения на загадочном острове, решая головоломки и общаясь по рации, — компактное и полностью бесплатное приключение для новичков и ветеранов серии.',
    cover: 'images/covers/we-were-here-expeditions-the-friendship-2023.jpg'
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = TITLES;
}
