// data.js
const TITLES = [
  {
    id: 'frieren-2023',
    title: "Frieren: Beyond Journey's End",
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон (2023, 28 серий) охватил ранние арки манги; второй сезон анонсирован и вышел в январе 2026 года.',
    year: 2023,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Эльфийка-магиня Фрирен, пережившая своих спутников по приключениям, заново открывает для себя, что значит ценить недолгую человеческую жизнь.',
    cover: 'images/covers/frieren-2023.jpg'
  },
  {
    id: 're-zero-starting-life-in-another-world-2016',
    title: 'Re:Zero − Starting Life in Another World',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло три сезона: первый в 2016-м, второй в 2020–2021-м, третий в двух частях — осенью 2024-го и весной 2025-го. Сюжет остановился в середине арки 7, продолжение официально не анонсировано.',
    year: 2016,
    genres: ['фэнтези', 'триллер'],
    rating: null,
    synopsis: 'Субару переносится в фэнтезийный мир и обнаруживает, что может возвращаться в прошлое после смерти — но каждый раз платит за это дорогую цену.',
    cover: 'images/covers/re-zero-starting-life-in-another-world-2016.jpg'
  },
  {
    id: 'the-boys-2019',
    title: 'The Boys',
    category: 'series',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло четыре сезона (2019–2024). Пятый сезон объявлен заключительным, отснят и ожидается в 2026 году — точная дата премьеры пока не подтверждена.',
    year: 2019,
    genres: ['сатира', 'боевик'],
    rating: null,
    synopsis: 'Группа мстителей без суперсил охотится на коррумпированных супергероев корпорации Vought.',
    cover: 'images/covers/the-boys-2019.jpg'
  },
  {
    id: 'ted-lasso-2020',
    title: 'Ted Lasso',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Три сезона (2020–2023) изначально задумывались как законченная история. В 2024 году Apple TV+ официально анонсировал четвёртый сезон с возвращением Джейсона Судейкиса; дата премьеры пока не объявлена.',
    year: 2020,
    genres: ['комедия', 'спорт'],
    rating: null,
    synopsis: 'Американский тренер по американскому футболу без опыта в футболе возглавляет английский клуб и меняет отношение команды друг к другу.',
    cover: 'images/covers/ted-lasso-2020.jpg'
  },
  {
    id: 'barbie-2023',
    title: 'Barbie',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['комедия', 'фэнтези'],
    rating: null,
    synopsis: 'Барби покидает идеальный Барбиленд и отправляется в реальный мир, где сталкивается с непростыми вопросами об идентичности.',
    cover: 'images/covers/barbie-2023.jpg'
  },
  {
    id: 'fight-club-1999',
    title: 'Fight Club',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1999,
    genres: ['драма', 'триллер'],
    rating: null,
    synopsis: 'Безымянный офисный работник и харизматичный продавец мыла Тайлер Дёрден основывают подпольный бойцовский клуб, который перерастает в нечто гораздо большее.',
    cover: 'images/covers/fight-club-1999.jpg'
  },
  {
    id: 'it-takes-two-2021',
    title: 'It Takes Two',
    category: 'game',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['кооператив', 'платформер'],
    rating: null,
    synopsis: 'Разводящиеся родители превращаются в кукол и должны пройти изобретательные кооперативные головоломки, чтобы вернуть себе человеческий облик.',
    cover: 'images/covers/it-takes-two-2021.jpg'
  },
  {
    id: 'baldurs-gate-3-2023',
    title: "Baldur's Gate 3",
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2023,
    genres: ['ролевая игра', 'фэнтези'],
    rating: null,
    synopsis: 'Партийная RPG по мотивам D&D: отряд заражённых мозговым паразитом иллитидов пытается остановить вторжение разума в Забытых Королевствах.',
    cover: 'images/covers/baldurs-gate-3-2023.jpg'
  },
  {
    id: 'tengen-toppa-gurren-lagann-2007',
    title: 'Tengen Toppa Gurren Lagann',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный телесериал 2007 года (27 серий) плюс два компиляционных фильма (2008–2009); продолжение не планируется.',
    year: 2007,
    genres: ['меха', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Симон и Камина сбегают из подземной деревни на пилотируемом роботе Лагann и присоединяются к восстанию против таинственных врагов на поверхности — история взросления перерастает в эпическую сагу о человеческой воле.',
    cover: 'images/covers/tengen-toppa-gurren-lagann-2007.png'
  },
  {
    id: 'demon-slayer-kimetsu-no-yaiba-2019',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 4 сезона (2019–2024) и первый фильм трилогии «Замок бесконечности» (2025); части 2 и 3 трилогии в производстве, точные даты выхода пока не объявлены.',
    year: 2019,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Тандзиро становится истребителем демонов, чтобы отомстить за погибшую семью и найти способ вернуть человеческий облик своей сестре Незуко, ставшей демоном.',
    cover: 'images/covers/demon-slayer-kimetsu-no-yaiba-2019.jpg'
  },
  {
    id: 'ride-your-wave-2019',
    title: 'Ride Your Wave',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2019,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'После гибели возлюбленного-серфингиста девушка обнаруживает, что может снова видеть и слышать его — но только когда рядом есть вода.',
    cover: 'images/covers/ride-your-wave-2019.jpg'
  },
  {
    id: 'witch-hat-atelier-2026',
    title: 'Witch Hat Atelier',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон вышел в апреле–июне 2026 года; второй сезон официально анонсирован и находится в производстве, дата премьеры пока не названа.',
    year: 2026,
    genres: ['фэнтези', 'драма', 'приключения'],
    rating: null,
    synopsis: 'Девочка Коко мечтает стать волшебницей в мире, где магии учат лишь избранных по рождению, — пока не встречает ведьму, владеющую тайным искусством рисованных заклинаний.',
    cover: 'images/covers/witch-hat-atelier-2026.jpg'
  },
  {
    id: 'cyberpunk-edgerunners-2022',
    title: 'Cyberpunk: Edgerunners',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Законченная десятисерийная история (2022). Отдельный сиквел «Cyberpunk: Edgerunners 2» с новыми персонажами анонсирован на осень 2026.',
    year: 2022,
    genres: ['боевик', 'драма', 'фантастика'],
    rating: null,
    synopsis: 'Уличный парень Дэвид Мартинес становится кибер-модифицированным наёмником-эджраннером, чтобы выжить в жестоком мире Найт-Сити, но каждая аугментация приближает его к безумию киберпсихоза.',
    cover: 'images/covers/cyberpunk-edgerunners-2022.jpg'
  },
  {
    id: 'a-silent-voice-2016',
    title: 'A Silent Voice',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Бывший школьный хулиган пытается искупить вину перед глухой одноклассницей, которую когда-то травил, и заново научиться понимать людей вокруг себя.',
    cover: 'images/covers/a-silent-voice-2016.jpg'
  },
  {
    id: 'josee-the-tiger-and-the-fish-2020',
    title: 'Josee, the Tiger and the Fish',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2020,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Студент подрабатывает помощником девушки, прикованной к инвалидному креслу и живущей в мире своих фантазий, и постепенно открывает для неё — и для себя — большой мир.',
    cover: 'images/covers/josee-the-tiger-and-the-fish-2020.jpg'
  },
  {
    id: 'your-name-2016',
    title: 'Your Name.',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Токийский парень и провинциальная школьница неожиданно начинают периодически меняться телами и постепенно понимают, что их связывает нечто большее, чем случайность.',
    cover: 'images/covers/your-name-2016.png'
  },
  {
    id: 'devil-may-cry-2025',
    title: 'Devil May Cry',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 2 сезона (2025, 2026); шоу продлено на третий и заключительный сезон «Paradiso», дата премьеры которого пока не объявлена.',
    year: 2025,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Получеловек-полудемон Данте сражается с силами ада, пытаясь остановить открытие врат в мир людей и разгадать тайну своего происхождения — взрослая экранизация культовой игровой серии от Netflix.',
    cover: 'images/covers/devil-may-cry-2025.jpg'
  },
  {
    id: 'shaman-king-2021',
    title: 'Shaman King',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Ремейк 2021 года завершён (52 серии, апрель 2022). Прямое продолжение «Shaman King: Flowers» (2024, 13 серий) тоже вышло полностью; дальнейшие анонсы пока касаются только манги.',
    year: 2021,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Ремейк классического аниме о мальчике-шамане Йо Асакуре, который готовится к турниру шаманов, чтобы стать королём духов и изменить мир.',
    cover: 'images/covers/shaman-king-2021.png'
  },
  {
    id: "jojo-s-bizarre-adventure-2012",
    title: "JoJo's Bizarre Adventure",
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Экранизация уже охватывает 7 из 9 частей манги (2012–2026, включая текущую «Steel Ball Run»); её продолжение выходит с осени 2026, а восьмая часть «JoJolion» пока официально не анонсирована.',
    year: 2012,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Многопоколенная сага о семье Джостар, чьи представители сражаются со сверхъестественными врагами при помощи уникальных способностей — Стендов.',
    cover: 'images/covers/jojo-s-bizarre-adventure-2012.jpg'
  },
  {
    id: 'noragami-2014',
    title: 'Noragami',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 2 сезона (2014, 2015) и OVA (2015). Несмотря на завершение манги в 2024 году, продолжение аниме официально не анонсировано.',
    year: 2014,
    genres: ['боевик', 'сверхъестественное', 'комедия'],
    rating: null,
    synopsis: 'Мелкий бог Ято мечтает о собственном святилище и толпах почитателей, а пока подрабатывает, выполняя случайные просьбы людей за пять йен, — пока не встречает школьницу Хиёри, застрявшую между миром людей и духов.',
    cover: 'images/covers/noragami-2014.jpg'
  },
  {
    id: 'violet-evergarden-2018',
    title: 'Violet Evergarden',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Телесериал (2018, 13 серий) и фильм-продолжение (2020) образуют завершённую историю; новых анонсов по сериалу нет.',
    year: 2018,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Бывшая девочка-солдат Виолетта Эвергарден устраивается автором писем на заказ и учится понимать человеческие чувства, включая смысл слов «я люблю тебя», сказанных ей человеком, которого она потеряла на войне.',
    cover: 'images/covers/violet-evergarden-2018.png'
  },
  {
    id: 'that-time-i-got-reincarnated-as-a-slime-2018',
    title: 'That Time I Got Reincarnated as a Slime',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 3 сезона (2018, 2021, 2023–2024) и полнометражный фильм (2022). Четвёртый сезон стартовал в апреле 2026 года и продлится до конца сентября 2026, параллельно вышел второй фильм (февраль 2026).',
    year: 2018,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Погибший японский офисный работник перерождается в фэнтезийном мире слизью и, получив уникальные способности, строит собственное государство монстров, где разные виды могут жить в мире.',
    cover: 'images/covers/that-time-i-got-reincarnated-as-a-slime-2018.jpg'
  },
  {
    id: "hell-s-paradise-jigokuraku-2023",
    title: "Hell's Paradise: Jigokuraku",
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 2 сезона (2023; январь–март 2026), адаптировано около 90 из 127 глав манги. Третий сезон ожидается, но студия MAPPA пока официально его не подтвердила.',
    year: 2023,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Приговорённый к смерти ниндзя Габимару получает шанс на помилование, если найдёт эликсир бессмертия на таинственном острове, кишащем чудовищами.',
    cover: 'images/covers/hell-s-paradise-jigokuraku-2023.jpg'
  },
  {
    id: 'chainsmoker-cat-2026',
    title: 'Chainsmoker Cat',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Премьера состоялась 3 июля 2026 года, сериал выходит еженедельно; данных о продлении на второй сезон пока нет.',
    year: 2026,
    genres: ['комедия', 'повседневность'],
    rating: null,
    synopsis: 'Кошкодевочка Яни с пагубной привычкой к курению никак не может навести порядок ни в квартире, ни в жизни — комедийное аниме по манге NyanNyanFactory, известное также под рабочим русским названием «Табакошка».',
    cover: 'images/covers/chainsmoker-cat-2026.jpg'
  },
  {
    id: 'a-new-dawn-2026',
    title: 'A New Dawn',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2026,
    genres: ['драма', 'мистика'],
    rating: null,
    synopsis: 'Режиссёрский дебют Ёситоси Синономии (аниматора «Твоего имени» и «Сада изящных слов») — история о двух друзьях детства, воссоединившихся у заброшенной фабрики фейерверков, которой грозит снос. В российском прокате известен под названием «И наступит рассвет».',
    cover: 'images/covers/a-new-dawn-2026.jpg'
  },
  {
    id: 'suzume-2022',
    title: 'Suzume',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2022,
    genres: ['приключения', 'фэнтези', 'мистика'],
    rating: null,
    synopsis: 'Школьница Судзумэ встречает загадочного юношу, ищущего двери, запечатывающие катастрофы, и вместе с говорящим стулом отправляется в путешествие по Японии, чтобы остановить бедствия, вырывающиеся из потустороннего мира.',
    cover: 'images/covers/suzume-2022.jpg'
  },
  {
    id: 'avatar-the-last-airbender-2005',
    title: 'Avatar: The Last Airbender (2005)',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Оригинальный мультсериал завершён тремя сезонами («Книгами») в 2005–2008 годах; прямого продолжения не выходило, только спин-оффы вроде «Легенды о Корре».',
    year: 2005,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Классический мультсериал Nickelodeon об Аанге — последнем аватаре, способном покорять все четыре стихии, который должен освоить магию воды, земли и огня, чтобы остановить Народ Огня и восстановить баланс в мире.',
    cover: 'images/covers/avatar-the-last-airbender-2005.jpg'
  },
  {
    id: 'avatar-the-last-airbender-2024',
    title: 'Avatar: The Last Airbender (2024)',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Netflix сразу продлил игровой ремейк на 2-й и 3-й (заключительный) сезоны. Сезон 2 вышел в июне 2026 года, сезон 3 уже отснят и находится на постпродакшене — дата премьеры пока не объявлена.',
    year: 2024,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Игровой ремейк культового мультсериала о мальчике-аватаре Аанге, который пробуждается спустя сто лет после начала войны Народа Огня и должен научиться покорять все стихии, чтобы спасти мир.',
    cover: 'images/covers/avatar-the-last-airbender-2024.jpg'
  },
  {
    id: 'castlevania-2017',
    title: 'Castlevania / Castlevania: Nocturne',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Оригинальный сериал «Castlevania» полностью завершён четырьмя сезонами (2017–2021). Сиквел-перезапуск «Castlevania: Nocturne» вышел двумя сезонами (2023, 2025) и с начала 2025 находится в подвешенном состоянии — Netflix официально не продлил и не закрыл его.',
    year: 2017,
    genres: ['тёмное фэнтези', 'боевик', 'ужасы'],
    rating: null,
    synopsis: 'Мрачная анимационная франшиза по мотивам видеоигр Castlevania: сперва Тревор Бельмонт сражается с вампиром Дракулой, объявившим войну человечеству, а затем — в «Nocturne» — новое поколение охотников противостоит тьме уже во Франции конца XVIII века.',
    cover: 'images/covers/castlevania-2017.jpg'
  },
  {
    id: 'the-legend-of-vox-machina-2022',
    title: 'The Legend of Vox Machina',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 4 сезона (2022–2026). Сериал продлён на пятый, заключительный сезон, премьера которого ожидается в 2027–2028 годах.',
    year: 2022,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Анимационная адаптация первой кампании настольного шоу Critical Role: банда из восьми неидеальных наёмников-героев Vox Machina защищает мир Экзандрии от тёмных магических сил.',
    cover: 'images/covers/the-legend-of-vox-machina-2022.jpg'
  },
  {
    id: 'the-mighty-nein-2025',
    title: 'The Mighty Nein',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон (8 серий) вышел в ноябре 2025 года. Второй сезон уже утверждён и почти полностью готов, но точная дата премьеры на Prime Video пока не объявлена.',
    year: 2025,
    genres: ['фэнтези', 'приключения', 'драма'],
    rating: null,
    synopsis: 'Анимационная экранизация второй кампании Critical Role: группа беглецов и изгоев из Волшебных Земель случайно завладевает могущественным артефактом и вынуждена объединиться, чтобы спасти реальность от катастрофы.',
    cover: 'images/covers/the-mighty-nein-2025.jpg'
  },
  {
    id: 'money-heist-2017',
    title: 'Money Heist (La Casa de Papel)',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Сериал полностью завершён пятью сезонами (2017–2021); финальный сезон вышел двумя частями. Продолжений на основных персонажах не запланировано.',
    year: 2017,
    genres: ['криминал', 'драма', 'триллер'],
    rating: null,
    synopsis: 'Загадочный человек по прозвищу Профессор собирает банду из восьми грабителей в масках Дали для беспрецедентного ограбления Королевского монетного двора Испании, которое перерастает в затяжное противостояние с полицией.',
    cover: 'images/covers/money-heist-2017.jpg'
  },
  {
    id: 'gen-v-2023',
    title: 'Gen V',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 2 сезона (2023, 2025). В апреле 2026 года Amazon официально закрыл сериал после двух сезонов; сюжетные линии персонажей продолжатся в «The Boys» и других проектах вселенной.',
    year: 2023,
    genres: ['супергерои', 'сатира', 'драма'],
    rating: null,
    synopsis: 'Спин-офф «Пацанов» о студентах Готолкинского университета — единственного колледжа для супергероев, — которые борются за популярность и оценки, пока не сталкиваются с чем-то куда более зловещим, творящимся за стенами кампуса.',
    cover: 'images/covers/gen-v-2023.jpg'
  },
  {
    id: 'masters-of-the-universe-revelation-2021',
    title: 'Masters of the Universe: Revelation / Revolution',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Обе мини-серии полностью вышли: «Revelation» — 10 эпизодов (2021), «Revolution» — 5 эпизодов (2024). История рассказана целиком, продолжение официально не анонсировано.',
    year: 2021,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Netflix-продолжение классической франшизы: Хи-Мэн и Скелетор сходятся в решающей битве за судьбу Этернии, а после его исхода на защиту планеты встаёт новое поколение защитников.',
    cover: 'images/covers/masters-of-the-universe-revelation-2021.jpg'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = TITLES;
}
