// data.js
const TITLES = [
  {
    id: 'frieren-2023',
    title: 'Фрирен, провожающая в последний путь',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон (2023, 28 серий) охватил ранние арки манги; второй сезон анонсирован и вышел в январе 2026 года.',
    year: 2023,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Эльфийка-магиня Фрирен, пережившая своих спутников по приключениям, заново открывает для себя, что значит ценить недолгую человеческую жизнь.',
    cover: 'images/covers/frieren-2023.jpg'
  },
  {
    id: 're-zero-starting-life-in-another-world-2016',
    title: 'Re:ZERO — Жизнь с нуля в альтернативном мире',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло три сезона: первый в 2016-м, второй в 2020–2021-м, третий в двух частях — осенью 2024-го и весной 2025-го. Сюжет остановился в середине арки 7, продолжение официально не анонсировано.',
    year: 2016,
    genres: ['фэнтези', 'триллер'],
    rating: null,
    synopsis: 'Субару переносится в фэнтезийный мир и обнаруживает, что может возвращаться в прошлое после смерти — но каждый раз платит за это дорогую цену.',
    cover: 'images/covers/re-zero-starting-life-in-another-world-2016.jpg'
  },
  {
    id: 'the-boys-2019',
    title: 'Пацаны',
    category: 'series',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло четыре сезона (2019–2024). Пятый сезон объявлен заключительным, отснят и ожидается в 2026 году — точная дата премьеры пока не подтверждена.',
    year: 2019,
    genres: ['сатира', 'боевик'],
    rating: null,
    synopsis: 'Группа мстителей без суперсил охотится на коррумпированных супергероев корпорации Vought.',
    cover: 'images/covers/the-boys-2019.jpg'
  },
  {
    id: 'ted-lasso-2020',
    title: 'Тед Лассо',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Три сезона (2020–2023) изначально задумывались как законченная история. В 2024 году Apple TV+ официально анонсировал четвёртый сезон с возвращением Джейсона Судейкиса; дата премьеры пока не объявлена.',
    year: 2020,
    genres: ['комедия', 'спорт'],
    rating: null,
    synopsis: 'Американский тренер по американскому футболу без опыта в футболе возглавляет английский клуб и меняет отношение команды друг к другу.',
    cover: 'images/covers/ted-lasso-2020.jpg'
  },
  {
    id: 'barbie-2023',
    title: 'Барби',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['комедия', 'фэнтези'],
    rating: null,
    synopsis: 'Барби покидает идеальный Барбиленд и отправляется в реальный мир, где сталкивается с непростыми вопросами об идентичности.',
    cover: 'images/covers/barbie-2023.jpg'
  },
  {
    id: 'fight-club-1999',
    title: 'Бойцовский клуб',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1999,
    genres: ['драма', 'триллер'],
    rating: null,
    synopsis: 'Безымянный офисный работник и харизматичный продавец мыла Тайлер Дёрден основывают подпольный бойцовский клуб, который перерастает в нечто гораздо большее.',
    cover: 'images/covers/fight-club-1999.jpg'
  },
  {
    id: 'it-takes-two-2021',
    title: 'It Takes Two',
    category: 'game',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['кооператив', 'платформер'],
    rating: null,
    synopsis: 'Разводящиеся родители превращаются в кукол и должны пройти изобретательные кооперативные головоломки, чтобы вернуть себе человеческий облик.',
    cover: 'images/covers/it-takes-two-2021.jpg'
  },
  {
    id: 'baldurs-gate-3-2023',
    title: "Baldur's Gate 3",
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2023,
    genres: ['ролевая игра', 'фэнтези'],
    rating: null,
    synopsis: 'Партийная RPG по мотивам D&D: отряд заражённых мозговым паразитом иллитидов пытается остановить вторжение разума в Забытых Королевствах.',
    cover: 'images/covers/baldurs-gate-3-2023.jpg'
  },
  {
    id: 'tengen-toppa-gurren-lagann-2007',
    title: 'Гуррен-Лаганн',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный телесериал 2007 года (27 серий) плюс два компиляционных фильма (2008–2009); продолжение не планируется.',
    year: 2007,
    genres: ['меха', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Симон и Камина сбегают из подземной деревни на пилотируемом роботе Лагann и присоединяются к восстанию против таинственных врагов на поверхности — история взросления перерастает в эпическую сагу о человеческой воле.',
    cover: 'images/covers/tengen-toppa-gurren-lagann-2007.png'
  },
  {
    id: 'demon-slayer-kimetsu-no-yaiba-2019',
    title: 'Клинок, рассекающий демонов',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 4 сезона (2019–2024) и первый фильм трилогии «Замок бесконечности» (2025); части 2 и 3 трилогии в производстве, точные даты выхода пока не объявлены.',
    year: 2019,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Тандзиро становится истребителем демонов, чтобы отомстить за погибшую семью и найти способ вернуть человеческий облик своей сестре Незуко, ставшей демоном.',
    cover: 'images/covers/demon-slayer-kimetsu-no-yaiba-2019.jpg'
  },
  {
    id: 'ride-your-wave-2019',
    title: 'На твоей волне',
    category: 'anime',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2019,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'После гибели возлюбленного-серфингиста девушка обнаруживает, что может снова видеть и слышать его — но только когда рядом есть вода.',
    cover: 'images/covers/ride-your-wave-2019.jpg'
  },
  {
    id: 'witch-hat-atelier-2026',
    title: 'Ателье колдовских колпаков',
    category: 'anime',
    status: 'done',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон вышел в апреле–июне 2026 года; второй сезон официально анонсирован и находится в производстве, дата премьеры пока не названа.',
    year: 2026,
    genres: ['фэнтези', 'драма', 'приключения'],
    rating: null,
    synopsis: 'Девочка Коко мечтает стать волшебницей в мире, где магии учат лишь избранных по рождению, — пока не встречает ведьму, владеющую тайным искусством рисованных заклинаний.',
    cover: 'images/covers/witch-hat-atelier-2026.jpg'
  },
  {
    id: 'cyberpunk-edgerunners-2022',
    title: 'Киберпанк: Бегущие по краю',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Законченная десятисерийная история (2022). Отдельный сиквел «Cyberpunk: Edgerunners 2» с новыми персонажами анонсирован на осень 2026.',
    year: 2022,
    genres: ['боевик', 'драма', 'фантастика'],
    rating: null,
    synopsis: 'Уличный парень Дэвид Мартинес становится кибер-модифицированным наёмником-эджраннером, чтобы выжить в жестоком мире Найт-Сити, но каждая аугментация приближает его к безумию киберпсихоза.',
    cover: 'images/covers/cyberpunk-edgerunners-2022.jpg'
  },
  {
    id: 'a-silent-voice-2016',
    title: 'Форма голоса',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Бывший школьный хулиган пытается искупить вину перед глухой одноклассницей, которую когда-то травил, и заново научиться понимать людей вокруг себя.',
    cover: 'images/covers/a-silent-voice-2016.jpg'
  },
  {
    id: 'josee-the-tiger-and-the-fish-2020',
    title: 'Её заветное желание',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2020,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Студент подрабатывает помощником девушки, прикованной к инвалидному креслу и живущей в мире своих фантазий, и постепенно открывает для неё — и для себя — большой мир.',
    cover: 'images/covers/josee-the-tiger-and-the-fish-2020.jpg'
  },
  {
    id: 'your-name-2016',
    title: 'Твоё имя',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2016,
    genres: ['драма', 'романтика'],
    rating: null,
    synopsis: 'Токийский парень и провинциальная школьница неожиданно начинают периодически меняться телами и постепенно понимают, что их связывает нечто большее, чем случайность.',
    cover: 'images/covers/your-name-2016.png'
  },
  {
    id: 'devil-may-cry-2025',
    title: 'Дьявол может плакать',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 2 сезона (2025, 2026); шоу продлено на третий и заключительный сезон «Paradiso», дата премьеры которого пока не объявлена.',
    year: 2025,
    genres: ['боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Получеловек-полудемон Данте сражается с силами ада, пытаясь остановить открытие врат в мир людей и разгадать тайну своего происхождения — взрослая экранизация культовой игровой серии от Netflix.',
    cover: 'images/covers/devil-may-cry-2025.jpg'
  },
  {
    id: 'shaman-king-2021',
    title: 'Король шаманов',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Ремейк 2021 года завершён (52 серии, апрель 2022). Прямое продолжение «Shaman King: Flowers» (2024, 13 серий) тоже вышло полностью; дальнейшие анонсы пока касаются только манги.',
    year: 2021,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Ремейк классического аниме о мальчике-шамане Йо Асакуре, который готовится к турниру шаманов, чтобы стать королём духов и изменить мир.',
    cover: 'images/covers/shaman-king-2021.png'
  },
  {
    id: "jojo-s-bizarre-adventure-2012",
    title: 'Невероятные приключения ДжоДжо',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Экранизация уже охватывает 7 из 9 частей манги (2012–2026, включая текущую «Steel Ball Run»); её продолжение выходит с осени 2026, а восьмая часть «JoJolion» пока официально не анонсирована.',
    year: 2012,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Многопоколенная сага о семье Джостар, чьи представители сражаются со сверхъестественными врагами при помощи уникальных способностей — Стендов.',
    cover: 'images/covers/jojo-s-bizarre-adventure-2012.jpg'
  },
  {
    id: 'noragami-2014',
    title: 'Бездомный Бог',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 2 сезона (2014, 2015) и OVA (2015). Несмотря на завершение манги в 2024 году, продолжение аниме официально не анонсировано.',
    year: 2014,
    genres: ['боевик', 'сверхъестественное', 'комедия'],
    rating: null,
    synopsis: 'Мелкий бог Ято мечтает о собственном святилище и толпах почитателей, а пока подрабатывает, выполняя случайные просьбы людей за пять йен, — пока не встречает школьницу Хиёри, застрявшую между миром людей и духов.',
    cover: 'images/covers/noragami-2014.jpg'
  },
  {
    id: 'violet-evergarden-2018',
    title: 'Вайолет Эвергарден',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Телесериал (2018, 13 серий) и фильм-продолжение (2020) образуют завершённую историю; новых анонсов по сериалу нет.',
    year: 2018,
    genres: ['драма', 'фэнтези'],
    rating: null,
    synopsis: 'Бывшая девочка-солдат Виолетта Эвергарден устраивается автором писем на заказ и учится понимать человеческие чувства, включая смысл слов «я люблю тебя», сказанных ей человеком, которого она потеряла на войне.',
    cover: 'images/covers/violet-evergarden-2018.png'
  },
  {
    id: 'that-time-i-got-reincarnated-as-a-slime-2018',
    title: 'О моём перерождении в слизь',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 3 сезона (2018, 2021, 2023–2024) и полнометражный фильм (2022). Четвёртый сезон стартовал в апреле 2026 года и продлится до конца сентября 2026, параллельно вышел второй фильм (февраль 2026).',
    year: 2018,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Погибший японский офисный работник перерождается в фэнтезийном мире слизью и, получив уникальные способности, строит собственное государство монстров, где разные виды могут жить в мире.',
    cover: 'images/covers/that-time-i-got-reincarnated-as-a-slime-2018.jpg'
  },
  {
    id: "hell-s-paradise-jigokuraku-2023",
    title: 'Адский рай',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 2 сезона (2023; январь–март 2026), адаптировано около 90 из 127 глав манги. Третий сезон ожидается, но студия MAPPA пока официально его не подтвердила.',
    year: 2023,
    genres: ['боевик', 'приключения', 'сверхъестественное'],
    rating: null,
    synopsis: 'Приговорённый к смерти ниндзя Габимару получает шанс на помилование, если найдёт эликсир бессмертия на таинственном острове, кишащем чудовищами.',
    cover: 'images/covers/hell-s-paradise-jigokuraku-2023.jpg'
  },
  {
    id: 'chainsmoker-cat-2026',
    title: 'Табакошка',
    category: 'anime',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Премьера состоялась 3 июля 2026 года, сериал выходит еженедельно; данных о продлении на второй сезон пока нет.',
    year: 2026,
    genres: ['комедия', 'повседневность'],
    rating: null,
    synopsis: 'Кошкодевочка Яни с пагубной привычкой к курению никак не может навести порядок ни в квартире, ни в жизни — комедийное аниме по манге NyanNyanFactory, известное также под рабочим русским названием «Табакошка».',
    cover: 'images/covers/chainsmoker-cat-2026.jpg'
  },
  {
    id: 'a-new-dawn-2026',
    title: 'И наступит рассвет',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2026,
    genres: ['драма', 'мистика'],
    rating: null,
    synopsis: 'Режиссёрский дебют Ёситоси Синономии (аниматора «Твоего имени» и «Сада изящных слов») — история о двух друзьях детства, воссоединившихся у заброшенной фабрики фейерверков, которой грозит снос. В российском прокате известен под названием «И наступит рассвет».',
    cover: 'images/covers/a-new-dawn-2026.jpg'
  },
  {
    id: 'suzume-2022',
    title: 'Судзумэ, закрывающая двери',
    category: 'anime',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: null,
    year: 2022,
    genres: ['приключения', 'фэнтези', 'мистика'],
    rating: null,
    synopsis: 'Школьница Судзумэ встречает загадочного юношу, ищущего двери, запечатывающие катастрофы, и вместе с говорящим стулом отправляется в путешествие по Японии, чтобы остановить бедствия, вырывающиеся из потустороннего мира.',
    cover: 'images/covers/suzume-2022.jpg'
  },
  {
    id: 'avatar-the-last-airbender-2005',
    title: 'Аватар: Легенда об Аанге (2005)',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Оригинальный мультсериал завершён тремя сезонами («Книгами») в 2005–2008 годах; прямого продолжения не выходило, только спин-оффы вроде «Легенды о Корре».',
    year: 2005,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Классический мультсериал Nickelodeon об Аанге — последнем аватаре, способном покорять все четыре стихии, который должен освоить магию воды, земли и огня, чтобы остановить Народ Огня и восстановить баланс в мире.',
    cover: 'images/covers/avatar-the-last-airbender-2005.jpg'
  },
  {
    id: 'avatar-the-last-airbender-2024',
    title: 'Аватар: Легенда об Аанге (2024)',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Netflix сразу продлил игровой ремейк на 2-й и 3-й (заключительный) сезоны. Сезон 2 вышел в июне 2026 года, сезон 3 уже отснят и находится на постпродакшене — дата премьеры пока не объявлена.',
    year: 2024,
    genres: ['приключения', 'фэнтези', 'боевик'],
    rating: null,
    synopsis: 'Игровой ремейк культового мультсериала о мальчике-аватаре Аанге, который пробуждается спустя сто лет после начала войны Народа Огня и должен научиться покорять все стихии, чтобы спасти мир.',
    cover: 'images/covers/avatar-the-last-airbender-2024.jpg'
  },
  {
    id: 'castlevania-2017',
    title: 'Кастлвания / Кастлвания: Ноктюрн',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Оригинальный сериал «Castlevania» полностью завершён четырьмя сезонами (2017–2021). Сиквел-перезапуск «Castlevania: Nocturne» вышел двумя сезонами (2023, 2025) и с начала 2025 находится в подвешенном состоянии — Netflix официально не продлил и не закрыл его.',
    year: 2017,
    genres: ['тёмное фэнтези', 'боевик', 'ужасы'],
    rating: null,
    synopsis: 'Мрачная анимационная франшиза по мотивам видеоигр Castlevania: сперва Тревор Бельмонт сражается с вампиром Дракулой, объявившим войну человечеству, а затем — в «Nocturne» — новое поколение охотников противостоит тьме уже во Франции конца XVIII века.',
    cover: 'images/covers/castlevania-2017.jpg'
  },
  {
    id: 'the-legend-of-vox-machina-2022',
    title: 'Легенда о Vox Machina',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Вышло 4 сезона (2022–2026). Сериал продлён на пятый, заключительный сезон, премьера которого ожидается в 2027–2028 годах.',
    year: 2022,
    genres: ['фэнтези', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Анимационная адаптация первой кампании настольного шоу Critical Role: банда из восьми неидеальных наёмников-героев Vox Machina защищает мир Экзандрии от тёмных магических сил.',
    cover: 'images/covers/the-legend-of-vox-machina-2022.jpg'
  },
  {
    id: 'the-mighty-nein-2025',
    title: 'Могучая девятка',
    category: 'series',
    status: 'queue',
    airingStatus: 'ongoing',
    seasonInfo: 'Первый сезон (8 серий) вышел в ноябре 2025 года. Второй сезон уже утверждён и почти полностью готов, но точная дата премьеры на Prime Video пока не объявлена.',
    year: 2025,
    genres: ['фэнтези', 'приключения', 'драма'],
    rating: null,
    synopsis: 'Анимационная экранизация второй кампании Critical Role: группа беглецов и изгоев из Волшебных Земель случайно завладевает могущественным артефактом и вынуждена объединиться, чтобы спасти реальность от катастрофы.',
    cover: 'images/covers/the-mighty-nein-2025.jpg'
  },
  {
    id: 'money-heist-2017',
    title: 'Бумажный дом',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Сериал полностью завершён пятью сезонами (2017–2021); финальный сезон вышел двумя частями. Продолжений на основных персонажах не запланировано.',
    year: 2017,
    genres: ['криминал', 'драма', 'триллер'],
    rating: null,
    synopsis: 'Загадочный человек по прозвищу Профессор собирает банду из восьми грабителей в масках Дали для беспрецедентного ограбления Королевского монетного двора Испании, которое перерастает в затяжное противостояние с полицией.',
    cover: 'images/covers/money-heist-2017.jpg'
  },
  {
    id: 'gen-v-2023',
    title: 'Поколение «Ви»',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 2 сезона (2023, 2025). В апреле 2026 года Amazon официально закрыл сериал после двух сезонов; сюжетные линии персонажей продолжатся в «The Boys» и других проектах вселенной.',
    year: 2023,
    genres: ['супергерои', 'сатира', 'драма'],
    rating: null,
    synopsis: 'Спин-офф «Пацанов» о студентах Готолкинского университета — единственного колледжа для супергероев, — которые борются за популярность и оценки, пока не сталкиваются с чем-то куда более зловещим, творящимся за стенами кампуса.',
    cover: 'images/covers/gen-v-2023.jpg'
  },
  {
    id: 'masters-of-the-universe-revelation-2021',
    title: 'Властелины вселенной: Откровение / Революция',
    category: 'series',
    status: 'queue',
    airingStatus: 'completed',
    seasonInfo: 'Обе мини-серии полностью вышли: «Revelation» — 10 эпизодов (2021), «Revolution» — 5 эпизодов (2024). История рассказана целиком, продолжение официально не анонсировано.',
    year: 2021,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Netflix-продолжение классической франшизы: Хи-Мэн и Скелетор сходятся в решающей битве за судьбу Этернии, а после его исхода на защиту планеты встаёт новое поколение защитников.',
    cover: 'images/covers/masters-of-the-universe-revelation-2021.jpg'
  },
  {
    id: 'the-amazing-spider-man-2012',
    title: 'Новый Человек-паук',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2012,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер получает суперспособности после укуса радиоактивного паука и, распутывая тайну исчезновения отца, впервые сталкивается с Ящером — учёным, одержимым генетическими экспериментами.',
    cover: 'images/covers/the-amazing-spider-man-2012.jpg'
  },
  {
    id: 'the-amazing-spider-man-2-2014',
    title: 'Новый Человек-паук: Высокое напряжение',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер пытается совмещать жизнь супергероя и отношения с Гвен Стейси, но городу угрожают электрический злодей Электро и бывший друг Гарри Озборн, вставший на путь Зелёного гоблина.',
    cover: 'images/covers/the-amazing-spider-man-2-2014.jpg'
  },
  {
    id: 'superman-2025',
    title: 'Супермен',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['фантастика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Молодой Супермен пытается совместить свою человечность с наследием криптонца, сражаясь с олигархом Лексом Лютором и отстаивая идеалы добра в циничном мире, — первый фильм новой киновселенной DC Джеймса Ганна.',
    cover: 'images/covers/superman-2025.jpg'
  },
  {
    id: 'the-gentlemen-2019',
    title: 'Джентльмены',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2019,
    genres: ['криминал', 'комедия', 'боевик'],
    rating: null,
    synopsis: 'Американец, построивший в Британии империю по выращиванию марихуаны, решает продать бизнес и отойти от дел, что запускает цепь интриг, шантажа и предательств среди лондонского криминального мира.',
    cover: 'images/covers/the-gentlemen-2019.jpg'
  },
  {
    id: 'the-man-from-u-n-c-l-e-2015',
    title: 'Агенты А.Н.К.Л.',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2015,
    genres: ['боевик', 'комедия', 'приключения'],
    rating: null,
    synopsis: 'В разгар Холодной войны агенты ЦРУ и КГБ вынуждены объединить усилия, чтобы остановить таинственную преступную организацию, стремящуюся завладеть ядерным оружием.',
    cover: 'images/covers/the-man-from-u-n-c-l-e-2015.jpg'
  },
  {
    id: 'eurotrip-2004',
    title: 'Евротур',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2004,
    genres: ['комедия', 'приключения'],
    rating: null,
    synopsis: 'Брошенный подругой выпускник школы отправляется вместе с друзьями в путешествие по Европе, чтобы найти немецкую переписчицу, в которую он неожиданно влюбился по интернету.',
    cover: 'images/covers/eurotrip-2004.jpg'
  },
  {
    id: 'the-hobbit-2012',
    title: 'Хоббит (трилогия)',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2012,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Хоббит Бильбо Бэггинс отправляется с волшебником Гэндальфом и отрядом гномов в опасное путешествие, чтобы отвоевать древнее королевство Эребор у дракона Смауга, — трилогия-приквел «Властелина колец».',
    cover: 'images/covers/the-hobbit-2012.jpg'
  },
  {
    id: 'drive-2011',
    title: 'Драйв',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2011,
    genres: ['криминал', 'драма', 'триллер'],
    rating: null,
    synopsis: 'Безымянный каскадёр и водитель на подработке ввязывается в ограбление, чтобы защитить соседку и её сына, и оказывается втянут в жестокое противостояние с криминальным миром Лос-Анджелеса.',
    cover: 'images/covers/drive-2011.jpg'
  },
  {
    id: 'the-batman-2022',
    title: 'Бэтмен',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2022,
    genres: ['боевик', 'детектив', 'триллер'],
    rating: null,
    synopsis: 'На втором году своей войны с преступностью Бэтмен расследует серию убийств, устроенных загадочным Риддлером, и раскрывает глубокую коррупцию, пронизывающую Готэм.',
    cover: 'images/covers/the-batman-2022.jpg'
  },
  {
    id: 'bullet-train-2022',
    title: 'Быстрее пули',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2022,
    genres: ['боевик', 'чёрная комедия', 'триллер'],
    rating: null,
    synopsis: 'Незадачливый наёмник по кличке Божья Коровка садится в скоростной японский поезд ради простого задания, но обнаруживает, что в вагонах едут ещё несколько убийц с пересекающимися и смертельно опасными миссиями.',
    cover: 'images/covers/bullet-train-2022.jpg'
  },
  {
    id: 'snatch-2000',
    title: 'Большой куш',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2000,
    genres: ['криминал', 'комедия', 'боевик'],
    rating: null,
    synopsis: 'Кража огромного бриллианта сталкивает лондонских бандитов, боксёров-нелегалов и цыганского боксёра по прозвищу Пуля в переплетении хаотичных и уморительных криминальных сюжетных линий.',
    cover: 'images/covers/snatch-2000.jpg'
  },
  {
    id: 'the-fountain-of-youth-2025',
    title: 'Источник вечной молодости',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['приключения', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Рассорившиеся брат и сестра объединяются в погоне за легендарным источником вечной молодости, спрятанным в череде опасных мест по всему миру.',
    cover: 'images/covers/the-fountain-of-youth-2025.jpg'
  },
  {
    id: 'jay-and-silent-bob-strike-back-2001',
    title: 'Джей и Молчаливый Боб наносят ответный удар',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2001,
    genres: ['комедия'],
    rating: null,
    synopsis: 'Узнав, что о них снимают фильм по комиксам без их разрешения и денег, Джей и Молчаливый Боб отправляются в Голливуд, чтобы сорвать съёмки, — комедийный привет всей киновселенной Кевина Смита.',
    cover: 'images/covers/jay-and-silent-bob-strike-back-2001.jpg'
  },
  {
    id: 'masters-of-the-universe-2026',
    title: 'Властелины Вселенной',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['фэнтези', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Принц Адам возвращается на порабощённую Скелетором Этернию и должен принять свою судьбу, превратившись в Хи-Мэна, чтобы освободить родную планету, — игровая экранизация классической франшизы.',
    cover: 'images/covers/masters-of-the-universe-2026.jpg'
  },
  {
    id: 'the-village-2004',
    title: 'Таинственный лес',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2004,
    genres: ['триллер', 'драма', 'мистика'],
    rating: null,
    synopsis: 'Жители изолированной деревни XIX века живут в страхе перед существами, обитающими в окружающем лесу, но попытка одной из девушек покинуть поселение раскрывает мрачную тайну этого места.',
    cover: 'images/covers/the-village-2004.jpg'
  },
  {
    id: 'orphan-2009',
    title: 'Дитя тьмы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2009,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Супружеская пара, потерявшая ребёнка, удочеряет девочку из приюта, но вскоре начинает подозревать, что с новой дочерью и её прошлым связано нечто зловещее.',
    cover: 'images/covers/orphan-2009.jpg'
  },
  {
    id: 'case-39-2009',
    title: 'Дело №39',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2009,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Социальный работник забирает к себе домой девочку, которую, как ей кажется, жестоко истязают собственные родители, но вскоре понимает, что настоящая опасность исходит от самого ребёнка.',
    cover: 'images/covers/case-39-2009.jpg'
  },
  {
    id: 'house-at-the-end-of-the-street-2012',
    title: 'Дом в конце улицы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2012,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Мать с дочерью переезжают в дом по соседству с местом, где несколько лет назад произошло жуткое убийство, и вскоре девушка сближается с выжившим членом той семьи, скрывающим страшную тайну.',
    cover: 'images/covers/house-at-the-end-of-the-street-2012.jpg'
  },
  {
    id: 'the-skeleton-key-2005',
    title: 'Ключ от всех дверей',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2005,
    genres: ['ужасы', 'триллер', 'мистика'],
    rating: null,
    synopsis: 'Сиделка устраивается на работу в старинный особняк в Луизиане и, обнаружив мастер-ключ, открывающий все двери дома, погружается в тайны, связанные с практиками худу.',
    cover: 'images/covers/the-skeleton-key-2005.jpg'
  },
  {
    id: 'klaustrofoby-2019',
    title: 'Клаустрофобы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2019,
    genres: ['ужасы', 'триллер'],
    rating: null,
    synopsis: 'Шестеро незнакомцев получают таинственное приглашение принять участие в эскейп-руме, который оказывается смертельно опасной игрой на выживание, где любая ошибка стоит жизни.',
    cover: 'images/covers/klaustrofoby-2019.jpg'
  },
  {
    id: 'red-dragon-2002',
    title: 'Красный дракон',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2002,
    genres: ['триллер', 'криминал', 'ужасы'],
    rating: null,
    synopsis: 'Бывший агент ФБР Уилл Грэм, вышедший на пенсию после поимки Ганнибала Лектера, вынужден вновь обратиться за помощью к гениальному маньяку, чтобы выследить нового серийного убийцу по прозвищу Зубная Фея.',
    cover: 'images/covers/red-dragon-2002.jpg'
  },
  {
    id: 'hannibal-2001',
    title: 'Ганнибал',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2001,
    genres: ['триллер', 'криминал', 'ужасы'],
    rating: null,
    synopsis: 'Спустя десять лет после побега Ганнибал Лектер ведёт размеренную жизнь в Италии, пока агент ФБР Кларис Старлинг и жаждущий мести богач-инвалид не начинают на него охоту.',
    cover: 'images/covers/hannibal-2001.jpg'
  },
  {
    id: 'hannibal-rising-2007',
    title: 'Ганнибал: Восхождение',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2007,
    genres: ['триллер', 'драма', 'криминал'],
    rating: null,
    synopsis: 'История юного Ганнибала Лектера, потерявшего семью во время войны и вставшего на путь мести убийцам своей сестры, — приквел, объясняющий рождение знаменитого маньяка.',
    cover: 'images/covers/hannibal-rising-2007.jpg'
  },
  {
    id: 'the-big-lebowski-1998',
    title: 'Большой Лебовски',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1998,
    genres: ['комедия', 'криминал'],
    rating: null,
    synopsis: 'Лос-анджелесский лежебока по прозвищу Чувак становится жертвой ошибки, когда бандиты, перепутав его с богатым тёзкой, портят его любимый ковёр, — и втягивается в абсурдную историю с похищением и выкупом.',
    cover: 'images/covers/the-big-lebowski-1998.jpg'
  },
  {
    id: 'alien-1979',
    title: 'Чужой',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1979,
    genres: ['фантастика', 'ужасы', 'триллер'],
    rating: null,
    synopsis: 'Экипаж грузового космического корабля «Ностромо» сталкивается на удалённой планете со смертоносным инопланетным существом, которое проникает на борт и начинает охотиться на людей одного за другим.',
    cover: 'images/covers/alien-1979.jpg'
  },
  {
    id: 'major-payne-1995',
    title: 'Майор Пэйн',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 1995,
    genres: ['комедия', 'военный'],
    rating: null,
    synopsis: 'Уволенный из армии за чрезмерную жестокость майор устраивается инструктором в кадетскую школу и пытается воспитать из недисциплинированных подростков настоящих бойцов, попутно узнавая, что такое дружба и забота.',
    cover: 'images/covers/major-payne-1995.jpg'
  },
  {
    id: 'tucker-dale-vs-evil-2010',
    title: 'Убойные каникулы',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2010,
    genres: ['комедия', 'ужасы'],
    rating: null,
    synopsis: 'Два добродушных, но неотёсанных приятеля отправляются на отдых в глухой лес, где компания студентов принимает их за маньяков-убийц, что приводит к цепи нелепых и кровавых недоразумений.',
    cover: 'images/covers/tucker-dale-vs-evil-2010.jpg'
  },
  {
    id: 'lilo-stitch-2025',
    title: 'Лило и Стич',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['фантастика', 'семейный', 'комедия'],
    rating: null,
    synopsis: 'Игровой ремейк классического мультфильма Disney: одинокая гавайская девочка Лило подружается с непослушным пришельцем Стичем, сбежавшим на Землю, и учит его, что значит быть частью настоящей семьи — «Оханы».',
    cover: 'images/covers/lilo-stitch-2025.jpg'
  },
  {
    id: 'baby-driver-2017',
    title: 'Малыш на драйве',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2017,
    genres: ['боевик', 'криминал', 'музыкальный'],
    rating: null,
    synopsis: 'Молодой талантливый водитель, работающий на криминального босса под звуки собственного плейлиста, пытается вырваться из преступного мира ради новой возлюбленной, но его втягивают в одно последнее опасное ограбление.',
    cover: 'images/covers/baby-driver-2017.jpg'
  },
  {
    id: 'split-fiction-2025',
    title: 'Split Fiction',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2025,
    genres: ['кооператив', 'приключение', 'экшен'],
    rating: null,
    synopsis: 'Две писательницы, Мио и Зои, попадают в ловушку внутри машины, похищающей творческие идеи, и вынуждены сообща пройти через миры их собственных научно-фантастических и фэнтезийных историй, чтобы найти выход.',
    cover: 'images/covers/split-fiction-2025.jpg'
  },
  {
    id: 'unravel-two-2018',
    title: 'Unravel Two',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2018,
    genres: ['кооператив', 'платформер', 'головоломка'],
    rating: null,
    synopsis: 'Два маленьких существа из пряжи, связанные общей нитью, оказываются выброшены на остров и учатся действовать сообща, преодолевая препятствия и головоломки в трогательной истории о дружбе и взаимовыручке.',
    cover: 'images/covers/unravel-two-2018.jpg'
  },
  {
    id: 'divinity-original-sin-2014',
    title: 'Divinity: Original Sin',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2014,
    genres: ['ролевая игра', 'пошаговая тактика'],
    rating: null,
    synopsis: 'Двое Охотников за Истоком расследуют убийство советника в городе Сайсил и постепенно раскрывают заговор, связанный с запретной магией Истока, сражаясь в пошаговых боях на изометрической карте мира Ривеллон.',
    cover: 'images/covers/divinity-original-sin-2014.jpg'
  },
  {
    id: 'divinity-original-sin-ii-2017',
    title: 'Divinity: Original Sin II',
    category: 'game',
    status: 'queue',
    airingStatus: null,
    year: 2017,
    genres: ['ролевая игра', 'пошаговая тактика'],
    rating: null,
    synopsis: 'Изгои-Истокорожденные пытаются выжить в мире, охваченном нашествием Пустоты, создавая собственного героя или выбирая одного из персонажей с уникальной предысторией и путешествуя по Ривеллону в пошаговых тактических сражениях.',
    cover: 'images/covers/divinity-original-sin-ii-2017.jpg'
  },
  {
    id: 'iron-man-2008',
    title: 'Железный человек',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2008,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Миллиардер и оружейный магнат Тони Старк создаёт бронированный костюм, чтобы вырваться из плена, и превращает его в оружие для борьбы со злом, став супергероем Железным человеком.',
    cover: 'images/covers/iron-man-2008.jpg'
  },
  {
    id: 'the-incredible-hulk-2008',
    title: 'Невероятный Халк',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2008,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Учёный Брюс Бэннер скрывается от военных и пытается найти лекарство от гнева, превращающего его в гигантского зелёного монстра Халка, но армия хочет заполучить его силу как оружие.',
    cover: 'images/covers/the-incredible-hulk-2008.jpg'
  },
  {
    id: 'iron-man-2-2010',
    title: 'Железный человек 2',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2010,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Тони Старк, чья личность Железного человека стала достоянием общественности, борется с опасным побочным эффектом технологии, поддерживающей его жизнь, и новыми врагами, жаждущими заполучить его разработки.',
    cover: 'images/covers/iron-man-2-2010.jpg'
  },
  {
    id: 'thor-2011',
    title: 'Тор',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2011,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Высокомерный бог грома Тор изгнан отцом Одином на Землю и лишён своей силы; чтобы вернуть её и защитить оба мира от заговора, ему предстоит научиться быть достойным своего молота.',
    cover: 'images/covers/thor-2011.jpg'
  },
  {
    id: 'captain-america-the-first-avenger-2011',
    title: 'Первый мститель',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2011,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Слабый, но отважный Стив Роджерс становится суперсолдатом Капитаном Америкой и сражается с нацистской организацией ГИДРА во время Второй мировой войны.',
    cover: 'images/covers/captain-america-the-first-avenger-2011.jpg'
  },
  {
    id: 'the-avengers-2012',
    title: 'Мстители',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2012,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Когда Локи похищает Тессеракт и угрожает Земле армией читаури, Ник Фьюри собирает команду супергероев — Железного человека, Тора, Капитана Америку, Халка и других — чтобы остановить вторжение.',
    cover: 'images/covers/the-avengers-2012.jpg'
  },
  {
    id: 'iron-man-3-2013',
    title: 'Железный человек 3',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2013,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После разрушительной атаки террориста Мандарина и пережитых в Нью-Йорке потрясений Тони Старк, лишившийся дома и брони, должен рассчитывать только на собственную изобретательность, чтобы защитить близких.',
    cover: 'images/covers/iron-man-3-2013.jpg'
  },
  {
    id: 'thor-the-dark-world-2013',
    title: 'Тор 2: Царство тьмы',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2013,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Тор должен спасти Вселенную от древнего зла — тёмного эльфа Малекита, который стремится погрузить все девять миров во тьму с помощью могущественного оружия Эфира.',
    cover: 'images/covers/thor-the-dark-world-2013.jpg'
  },
  {
    id: 'captain-america-the-winter-soldier-2014',
    title: 'Первый мститель: Другая война',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Стив Роджерс обнаруживает, что организация Щ.И.Т. поражена изнутри Гидрой, и вынужден противостоять таинственному наёмному убийце по прозвищу Зимний солдат.',
    cover: 'images/covers/captain-america-the-winter-soldier-2014.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-2014',
    title: 'Стражи Галактики',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2014,
    genres: ['фантастика', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Авантюрист Питер Квилл становится мишенью охотников за головами после кражи таинственной сферы и вынужден объединиться со странной компанией изгоев, чтобы спасти галактику.',
    cover: 'images/covers/guardians-of-the-galaxy-2014.jpg'
  },
  {
    id: 'avengers-age-of-ultron-2015',
    title: 'Мстители: Эра Альтрона',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2015,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Тони Старк создаёт искусственный интеллект Альтрона для защиты Земли, но программа выходит из-под контроля и решает, что для спасения планеты человечество нужно уничтожить.',
    cover: 'images/covers/avengers-age-of-ultron-2015.jpg'
  },
  {
    id: 'ant-man-2015',
    title: 'Человек-муравей',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2015,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Мелкий вор Скотт Лэнг получает от учёного Хэнка Пима костюм, позволяющий уменьшаться до размеров насекомого при сохранении силы удара, и должен использовать эту способность ради спасительного ограбления.',
    cover: 'images/covers/ant-man-2015.jpg'
  },
  {
    id: 'captain-america-civil-war-2016',
    title: 'Первый мститель: Противостояние',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2016,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Разногласия по поводу государственного контроля над супергероями раскалывают Мстителей на два враждующих лагеря во главе с Капитаном Америкой и Железным человеком.',
    cover: 'images/covers/captain-america-civil-war-2016.jpg'
  },
  {
    id: 'doctor-strange-2016',
    title: 'Доктор Стрэндж',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2016,
    genres: ['фэнтези', 'супергероика', 'боевик'],
    rating: null,
    synopsis: 'Блестящий, но самонадеянный нейрохирург Стивен Стрэндж после автокатастрофы, лишившей его рук, отправляется на поиски исцеления и открывает для себя мир магии и параллельных измерений.',
    cover: 'images/covers/doctor-strange-2016.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-vol-2-2017',
    title: 'Стражи Галактики. Часть 2',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['фантастика', 'приключения', 'комедия'],
    rating: null,
    synopsis: 'Стражи Галактики отправляются на поиски таинственного отца Питера Квилла и попутно защищают новообретённую семью от предательства и новых врагов.',
    cover: 'images/covers/guardians-of-the-galaxy-vol-2-2017.jpg'
  },
  {
    id: 'spider-man-homecoming-2017',
    title: 'Человек-паук: Возвращение домой',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Питер Паркер пытается совмещать школьную жизнь с обязанностями супергероя под присмотром Тони Старка, попутно раскрывая заговор торговца оружием Стервятника.',
    cover: 'images/covers/spider-man-homecoming-2017.jpg'
  },
  {
    id: 'thor-ragnarok-2017',
    title: 'Тор: Рагнарёк',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2017,
    genres: ['фэнтези', 'супергероика', 'комедия'],
    rating: null,
    synopsis: 'Лишённый молота и заточённый на планете-свалке Сакааре, Тор должен успеть вернуться в Асгард и остановить свою сестру Хелу, богиню смерти, несущую Рагнарёк — конец света.',
    cover: 'images/covers/thor-ragnarok-2017.jpg'
  },
  {
    id: 'black-panther-2018',
    title: 'Чёрная пантера',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После смерти отца Т’Чалла возвращается в технологически передовое африканское королевство Ваканда, чтобы занять трон, но сталкивается с претендентом, ставящим под угрозу судьбу страны и всего мира.',
    cover: 'images/covers/black-panther-2018.jpg'
  },
  {
    id: 'avengers-infinity-war-2018',
    title: 'Мстители: Война бесконечности',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Мстители и их союзники объединяются, чтобы остановить безумного титана Таноса, собирающего Камни Бесконечности ради уничтожения половины всего живого во Вселенной.',
    cover: 'images/covers/avengers-infinity-war-2018.jpg'
  },
  {
    id: 'ant-man-and-the-wasp-2018',
    title: 'Человек-муравей и Оса',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2018,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Скотт Лэнг вновь надевает костюм Человека-муравья и объединяется с Хоуп ван Дайн, ставшей Осой, чтобы спасти её мать из Квантовой сферы, где она пропала много лет назад.',
    cover: 'images/covers/ant-man-and-the-wasp-2018.jpg'
  },
  {
    id: 'captain-marvel-2019',
    title: 'Капитан Марвел',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Пилот военно-космических сил Кри Вирс Данверс, обретя сверхспособности, оказывается в центре межгалактического конфликта и постепенно вспоминает своё прошлое на Земле.',
    cover: 'images/covers/captain-marvel-2019.jpg'
  },
  {
    id: 'avengers-endgame-2019',
    title: 'Мстители: Финал',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'После уничтожения половины Вселенной оставшиеся Мстители разрабатывают отчаянный план с использованием путешествий во времени, чтобы отменить деяния Таноса и вернуть погибших.',
    cover: 'images/covers/avengers-endgame-2019.jpg'
  },
  {
    id: 'spider-man-far-from-home-2019',
    title: 'Человек-паук: Вдали от дома',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2019,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'Питер Паркер отправляется на каникулы в Европу, но вынужден вернуться к обязанностям супергероя, когда Ник Фьюри просит его помочь остановить нападения загадочных существ из стихий.',
    cover: 'images/covers/spider-man-far-from-home-2019.jpg'
  },
  {
    id: 'black-widow-2021',
    title: 'Чёрная вдова',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Наташа Романофф сталкивается с тёмным прошлым, когда всплывает опасная заговорщическая организация, связывающая её с семьёй шпионов, вырастившей её, и требующая закрыть счёты.',
    cover: 'images/covers/black-widow-2021.jpg'
  },
  {
    id: 'shang-chi-and-the-legend-of-the-ten-rings-2021',
    title: 'Шан-Чи и легенда десяти колец',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'Шан-Чи, мастер боевых искусств, скрывающийся от прошлого, вынужден противостоять своему отцу — лидеру тайной организации, владеющему десятью кольцами безграничной силы.',
    cover: 'images/covers/shang-chi-and-the-legend-of-the-ten-rings-2021.jpg'
  },
  {
    id: 'eternals-2021',
    title: 'Вечные',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'фантастика', 'фэнтези'],
    rating: null,
    synopsis: 'Раскрытые бессмертные существа, тысячелетиями тайно жившие среди людей, вынуждены вновь объединиться, чтобы защитить человечество от древних чудовищ Девиантов.',
    cover: 'images/covers/eternals-2021.jpg'
  },
  {
    id: 'spider-man-no-way-home-2021',
    title: 'Человек-паук: Нет пути домой',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2021,
    genres: ['супергероика', 'боевик', 'фэнтези'],
    rating: null,
    synopsis: 'После раскрытия личности Человека-паука Питер Паркер просит Доктора Стрэнджа стереть эту тайну из памяти людей, но неудачное заклинание открывает мультивселенную и впускает опасных врагов из других реальностей.',
    cover: 'images/covers/spider-man-no-way-home-2021.jpg'
  },
  {
    id: 'doctor-strange-in-the-multiverse-of-madness-2022',
    title: 'Доктор Стрэндж: В мультивселенной безумия',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['фэнтези', 'супергероика', 'ужасы'],
    rating: null,
    synopsis: 'Доктор Стрэндж вместе с юной Америкой Чавес, способной путешествовать между вселенными, отправляется в опасное путешествие по мультивселенной, спасаясь от могущественного врага, охотящегося за её силой.',
    cover: 'images/covers/doctor-strange-in-the-multiverse-of-madness-2022.jpg'
  },
  {
    id: 'thor-love-and-thunder-2022',
    title: 'Тор: Любовь и гром',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['фэнтези', 'супергероика', 'комедия'],
    rating: null,
    synopsis: 'Тор пытается обрести внутренний покой, но вынужден вернуться в бой, когда Голод Богов начинает истреблять богов по всей Вселенной, а его бывшая возлюбленная Джейн Фостер обретает силу Тора.',
    cover: 'images/covers/thor-love-and-thunder-2022.jpg'
  },
  {
    id: 'black-panther-wakanda-forever-2022',
    title: 'Чёрная Пантера: Ваканда навсегда',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2022,
    genres: ['супергероика', 'боевик', 'драма'],
    rating: null,
    synopsis: 'После смерти короля Т’Чаллы королева Рамонда и защитники Ваканды должны отстоять независимость страны от новых угроз, включая подводное королевство Талокан во главе с Нэмором.',
    cover: 'images/covers/black-panther-wakanda-forever-2022.jpg'
  },
  {
    id: 'ant-man-and-the-wasp-quantumania-2023',
    title: 'Человек-муравей и Оса: Квантомания',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Семья Лэнг случайно оказывается заброшена в Квантовую сферу, где сталкивается с могущественным завоевателем Кэнгом, чьи планы угрожают не только их миру, но и всей мультивселенной.',
    cover: 'images/covers/ant-man-and-the-wasp-quantumania-2023.jpg'
  },
  {
    id: 'guardians-of-the-galaxy-vol-3-2023',
    title: 'Стражи Галактики. Часть 3',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['фантастика', 'приключения', 'боевик'],
    rating: null,
    synopsis: 'Стражи Галактики отправляются в опасную миссию, чтобы спасти жизнь Ракеты, и попутно раскрывают тёмную историю его создания корпорацией «Верховная эволюция».',
    cover: 'images/covers/guardians-of-the-galaxy-vol-3-2023.jpg'
  },
  {
    id: 'the-marvels-2023',
    title: 'Марвелы',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2023,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Капитан Марвел, Мисс Марвел и Моника Рэмбо случайно меняются местами каждый раз при использовании своих сил и вынуждены объединиться, чтобы вместе остановить новую угрозу галактике.',
    cover: 'images/covers/the-marvels-2023.jpg'
  },
  {
    id: 'deadpool-wolverine-2024',
    title: 'Дэдпул и Росомаха',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2024,
    genres: ['супергероика', 'боевик', 'комедия'],
    rating: null,
    synopsis: 'Уэйд Уилсон попадает в поле зрения Управления временными изменениями и вынужден уговорить недовольного жизнью Росомаху помочь ему спасти собственную реальность от уничтожения.',
    cover: 'images/covers/deadpool-wolverine-2024.jpg'
  },
  {
    id: 'captain-america-brave-new-world-2025',
    title: 'Капитан Америка: Новый мир',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Новый Капитан Америка Сэм Уилсон оказывается втянут в международный заговор, когда покушение на президента США заставляет его выяснить, кто пытается разжечь мировую войну.',
    cover: 'images/covers/captain-america-brave-new-world-2025.jpg'
  },
  {
    id: 'thunderbolts-2025',
    title: 'Громовержцы*',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Группа бывших наёмников, шпионов и антигероев, преданных собственным правительством, вынуждена объединиться в опасную команду, чтобы выжить и раскрыть тёмную тайну.',
    cover: 'images/covers/thunderbolts-2025.jpg'
  },
  {
    id: 'the-fantastic-four-first-steps-2025',
    title: 'Фантастическая четвёрка: Первые шаги',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2025,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'В ретрофутуристическом 1960-х Реед Ричардс, Сью Шторм, Джонни Шторм и Бен Гримм, обретшие сверхспособности после космической экспедиции, должны защитить Землю от пожирателя планет Галактуса.',
    cover: 'images/covers/the-fantastic-four-first-steps-2025.jpg'
  },
  {
    id: 'spider-man-brand-new-day-2026',
    title: 'Человек-паук: Новый день',
    category: 'movie',
    status: 'done',
    airingStatus: null,
    year: 2026,
    genres: ['супергероика', 'боевик', 'приключения'],
    rating: null,
    synopsis: 'После событий «Нет пути домой» Питер Паркер, забытый всем миром, пытается заново выстроить жизнь и отношения, оставаясь Человеком-пауком и сталкиваясь с новыми врагами.',
    cover: 'images/covers/spider-man-brand-new-day-2026.jpg'
  },
  {
    id: 'avengers-doomsday-2026',
    title: 'Мстители: Судный день',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2026,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Герои из трёх разных вселенных оказываются на пути столкновения с небывалой угрозой в лице Виктора фон Дума — в этой роли на экран возвращается Роберт Дауни-младший, ранее игравший Тони Старка.',
    cover: 'images/covers/avengers-doomsday-2026.jpg'
  },
  {
    id: 'avengers-secret-wars-2027',
    title: 'Мстители: Секретные войны',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2027,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Финал Саги Мультивселенной: герои и злодеи Marvel сходятся в решающей битве с Доктором Думом на арене, вдохновлённой комиксовым Battleworld, — режиссёры Энтони и Джо Руссо завершают историю, начатую в «Судном дне».',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'x-men-2028',
    title: 'Люди Икс',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'фантастика'],
    rating: null,
    synopsis: 'Перезапуск истории о мутантах внутри MCU после событий «Секретных войн»: новый актёрский состав во главе с Джин Грей и Циклопом, представленный режиссёром Джейком Шрайером.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'ghost-rider-2028',
    title: 'Призрачный гонщик',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'мистика'],
    rating: null,
    synopsis: 'Джонни Блейз заключает сделку с дьяволом и становится Призрачным гонщиком — байкером-мстителем с горящим черепом — в отдельном фильме Marvel Studios с Райаном Гослингом в главной роли, режиссёр Шон Леви.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'black-panther-iii-2028',
    title: 'Чёрная пантера 3',
    category: 'movie',
    status: 'queue',
    airingStatus: null,
    year: 2028,
    genres: ['супергероика', 'боевик', 'драма'],
    rating: null,
    synopsis: 'Повзрослевший сын Т’Чаллы принимает мантию Чёрной пантеры и наследие Ваканды — третий фильм франшизы Райана Куглера, с Дэвидом Джонссоном в главной роли.',
    cover: 'images/covers/_placeholder.svg'
  },
  {
    id: 'wandavision-2021',
    title: 'Ванда/Вижн',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный минисериал (2021, 9 серий); продолжения не выходило, но история Ванды и Вижна получила развитие в спин-оффах «Это всё Агата» и «Квест Вижна».',
    year: 2021,
    genres: ['супергероика', 'драма', 'мистика'],
    rating: null,
    synopsis: 'Ванда Максимофф и Вижн живут идиллической жизнью в пригороде, где реальность подозрительно напоминает классические американские ситкомы разных десятилетий, — но за фасадом благополучия скрывается куда более мрачная тайна.',
    cover: 'images/covers/wandavision-2021.webp'
  },
  {
    id: 'the-falcon-and-the-winter-soldier-2021',
    title: 'Сокол и Зимний солдат',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный минисериал (2021, 6 серий); второго сезона не последовало — сюжетные линии героев продолжились в фильме «Капитан Америка: Новый мир».',
    year: 2021,
    genres: ['супергероика', 'боевик', 'триллер'],
    rating: null,
    synopsis: 'Сэм Уилсон и Баки Барнс объединяются, чтобы остановить группировку «Флаг-крушители» и разобраться с наследием щита Капитана Америка, оставшегося без хозяина.',
    cover: 'images/covers/the-falcon-and-the-winter-soldier-2021.webp'
  },
  {
    id: 'loki-2021',
    title: 'Локи',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 2 сезона (2021, 2023); шоу завершено на достигнутой точке, третий сезон официально не анонсирован — хотя герой вернётся в третьем сезоне «Что, если...?».',
    year: 2021,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'Похищенный после кражи Тессеракта бог обмана попадает в Управление временными изменениями, где вынужден помогать в охоте на опасный вариант самого себя, распутывая заговор вокруг Священной временной линии.',
    cover: 'images/covers/loki-2021.webp'
  },
  {
    id: 'what-if-2021',
    title: 'Что, если...?',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Вышло 3 сезона (2021, 2023, 2024); Marvel объявила третий сезон финальным, продолжения не планируется.',
    year: 2021,
    genres: ['супергероика', 'фантастика', 'приключения'],
    rating: null,
    synopsis: 'Анимационная антология альтернативных вселенных Marvel: всевидящий Наблюдатель проводит зрителя через сценарии, в которых знаковые события киновселенной пошли по другому пути.',
    cover: 'images/covers/what-if-2021.webp'
  },
  {
    id: 'hawkeye-2021',
    title: 'Соколиный глаз',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный минисериал (2021, 6 серий); второй сезон не анонсирован, линия Кейт Бишоп продолжилась в спин-оффе «Эхо».',
    year: 2021,
    genres: ['супергероика', 'боевик', 'детектив'],
    rating: null,
    synopsis: 'Клинт Бартон готовится вернуться домой на Рождество, но оказывается втянут в криминальные разборки Нью-Йорка вместе с начинающей лучницей Кейт Бишоп, которая мечтает стать супергероем.',
    cover: 'images/covers/hawkeye-2021.webp'
  },
  {
    id: 'moon-knight-2022',
    title: 'Лунный рыцарь',
    category: 'series',
    status: 'done',
    airingStatus: 'completed',
    seasonInfo: 'Законченный минисериал (2022, 6 серий); второй сезон официально не подтверждён — Marvel планирует вернуть героя в других проектах, но не в отдельном сезоне.',
    year: 2022,
    genres: ['супергероика', 'мистика', 'триллер'],
    rating: null,
    synopsis: 'Тихий работник музейного магазина Стивен Грант обнаруживает, что делит тело и сознание с наёмником Марком Спектором — аватаром древнего египетского бога луны Хонсу.',
    cover: 'images/covers/moon-knight-2022.webp'
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = TITLES;
}
